---
title: "Analyse libellenmeetnetten"
author: 
    name: "Toon Westra, Geert De Knijf, Sam Van De Poel,  Frederic Piesschaert, Thierry Onkelinx"
    email: "Toon.Westra@inbo.be"
subtitle: "Technisch rapport"
format: 
  html:
    embed-resources: true
editor: source
toc: true
number-sections: true
code-fold: true
lang: nl
execute:
  echo: false
  warning: false
---

```{r}
#|label: "setup"  
#|output: false

library(knitr)
options(knitr.kable.NA = '')
opts_chunk$set(
  echo = TRUE,
  cache = FALSE,
  warning = FALSE,
  message = FALSE
)

library(tidyverse)
library(INBOtheme)
library(INBOmd)
library(sf)
library(INLA)
library(inlatools)
library(kableExtra)
library(units)
library(effectclass)
library(openssl)
library(git2rdata)
library(n2khab)
library(DT)
library(here)

conflicted::conflicts_prefer(dplyr::filter)
conflicted::conflicts_prefer(dplyr::lag)
conflicted::conflicts_prefer(tidyr::expand)
```

```{r}
#|label: "load functions"

path_functions <- fileman_up("soortenmeetnetten-analysis")

source(file.path(path_functions, "source/functions_smp.R"))

```
