# Plannning

```{r}

year_planning <- 2026

werkpakketten_locaties <- read_vc(root = fileman_up("soortenmeetnetten-queries"),
                               file =  "raw/werkpakketten_locaties")

evaluatie_locaties_cyclus <- evaluatie_locaties %>%
  filter(duur_meetcyclus == 3) %>%
  group_by(meetnet) %>%
  filter(meetcyclus == max(meetcyclus)) %>%
  ungroup() %>%
  group_by(meetnet, locatie, protocol, meetcyclus) %>%
  summarise(voldoende_geteld_cyclus = sum(voldoende_geteld) > 0,
         voldoende_data_cyclus = sum(voldoende_data) > 0,
         max_n_tellingen = max(aantal_tellingen_jaardoel),
         jaar = str_c(jaar, collapse = "; "),
         min_jaar = min(jaar)) %>%
  ungroup()

werkpakketten_locaties_cyclus <- werkpakketten_locaties %>%
  mutate(jaar_werkpakket = as.numeric(str_sub(werkpakket, start = -4))) %>%
  left_join(distinct(evaluatie_locaties_cyclus, meetnet, min_jaar), by = c("meetnet")) %>%
  filter(jaar_werkpakket >= min_jaar) %>%
  select(-min_jaar)

meetnet_protocol <- evaluatie_locaties_cyclus %>%
  distinct(meetnet, protocol, meetcyclus)

overzicht_locaties_cyclus <- locaties_metadata %>%
  inner_join(meetnet_protocol, by = c("meetnet")) %>%
  left_join(evaluatie_locaties_cyclus, by = c("meetnet", "protocol", "locatie", "meetcyclus")) %>%
  mutate(voldoende_geteld_cyclus = ifelse(is.na(voldoende_geteld_cyclus), FALSE, voldoende_geteld_cyclus),
         voldoende_data_cyclus = ifelse(is.na(voldoende_data_cyclus), FALSE, voldoende_data_cyclus)) %>%
  left_join(werkpakketten_locaties_cyclus, by = c("meetnet", "locatie"))
  
overzicht_locaties_cyclus_unique <- overzicht_locaties_cyclus %>%
  group_by(meetnet, protocol, locatie, is_active, is_sample, meetcyclus, voldoende_geteld_cyclus, voldoende_data_cyclus, jaar, min_jaar) %>%
  summarise(jaar_werkpakket = str_c(unique(jaar_werkpakket), collapse = ";"))

```
```{r}
evaluatie_kam_fuiken <- overzicht_locaties_cyclus_unique %>%
  filter(meetnet == "Kamsalamander") %>%
  filter(is_sample, is_active) %>%
  mutate(status = ifelse(voldoende_data_cyclus, "OK, voldoende data",
                         ifelse(str_detect(jaar_werkpakket, "2026") & !is.na(jaar_werkpakket), "OK, planning 2026",
                                ifelse(voldoende_geteld_cyclus, "Voldoende bezocht, onvoldoende data: herbezoeken?", 
                                       ifelse(!is.na(jaar_werkpakket), "Toevoegen aan werkpakket 2026", 
                                              ifelse(is.na(jaar_werkpakket),"Nieuwe locatie: Toevoegen aan werkpakket 2026?", NA))))))

evaluatie_kam_fuiken %>%
  write_csv2("../output/kamsalamander_status_2026.csv")
```

