
# Dataverkenning Knoflookpad

## Overzicht aantallen

### Adulten

```{r}

analyseset_roepkoren_vroedmeesterpad <- read_vc(file = "analyseset_vroedmeesterpad_roepkoren", root = "../output/analyseset")

```

```{r}
analyseset_roepkoren_vroedmeesterpad %>%
  ggplot(aes(x = jaar, y = aantal, colour = is_sample)) +
  geom_point(alpha = 0.3) +
  stat_summary(fun.data = "mean_cl_boot", colour = "red", size = 1, alpha = 0.5) +
  facet_wrap(~ levensstadium, scales = "free_y")
```

### Per locatie

```{r}
overzicht_locatie <- analyseset_roepkoren_vroedmeesterpad %>%
  filter(primaire_soort) %>%
  group_by(locatie, jaar) %>%
  summarise(aantal_gemiddeld = round(mean(aantal), 1)) %>%
  ungroup()

overzicht_wide <- overzicht_locatie %>%
  arrange(jaar) %>%
  pivot_wider(names_from = "jaar", values_from = aantal_gemiddeld)

```

```{r}
overzicht_wide %>%
  arrange(locatie) %>%
  kable(caption = "gemiddeld aantal geteld per jaar en per locatie") %>%
  kable_styling()
```

 
### Larven

```{r}

analyseset_larven_vroedmeesterpad <- read_vc(file = "analyseset_vroedmeesterpad_larven", root = "../output/analyseset")

larven_totaal <- analyseset_larven_vroedmeesterpad %>%
  group_by(meetnet, locatie, datum, jaar, soort_nl, primaire_soort) %>%
  summarise(aantal = sum(aantal),
            aantal_geschept = sum(n_catch),
            n_subloc = n()) %>%
  ungroup()
```

```{r}
larven_totaal %>%
  filter(primaire_soort) %>%
  ggplot(aes(x = jaar, y = aantal)) +
  geom_point(alpha = 0.3) +
  stat_summary(fun.data = "mean_cl_boot", colour = "red", size = 1, alpha = 0.5) 
```

### Per locatie

```{r}
overzicht_locatie <- larven_totaal %>%
  filter(primaire_soort) %>%
  group_by(locatie, jaar) %>%
  summarise(aantal_gemiddeld = round(mean(aantal), 1)) %>%
  ungroup()

overzicht_wide <- overzicht_locatie %>%
  arrange(jaar) %>%
  pivot_wider(names_from = "jaar", values_from = aantal_gemiddeld)

```

```{r}
overzicht_wide %>%
  arrange(locatie) %>%
  kable(caption = "gemiddeld aantal geteld per jaar en per locatie") %>%
  kable_styling()
```
