# Data

We maken gebruik van de data ingezameld via [meetnetten.be](www.meetnetten.be).

```{r}

visits_hazelmuis <- get_visits_smp() %>%
  filter(meetnet == "Hazelmuis - Nestbuizen")

hazelmuis_nestbuis_orig <- read_vc("raw/aantal_hazelmuis_nestbuizen", root = data_path) %>%
  mutate(visit_id = as.numeric(visit_id))

hazelmuis_nestbuis_bezoek <- visits_hazelmuis %>%
  select(visit_id, bezoek_status, voor_analyse) %>%
  left_join(hazelmuis_nestbuis_orig, by = c("visit_id")) %>%
  select(meetnet, locatie, sublocatie, datum, voor_analyse, visit_id, sample_id, niet_geteld, soort_nl, levensstadium, activiteit, observation_type, code, description, aantal) %>%
  filter(!niet_geteld)

```

## Dataverkenning

```{r}
hazelmuis_nestbuis_bezoek %>%
  distinct(meetnet, locatie, sublocatie) %>%
  ggplot(aes(x = locatie)) +
  geom_bar() +
  coord_flip() +
  labs(y = "Aantal nestbuizen")
```



```{r}
n_species_nestbuis <- hazelmuis_nestbuis_bezoek %>%
  group_by(visit_id, sample_id, locatie, sublocatie, datum) %>%
  mutate(n_species = n_distinct(soort_nl)) %>%
  ungroup() %>%
  filter(n_species > 1)
``` 

```{r, fig.width= 10, fig.cap= "Voorkomen per bezoek"}
hazelmuis_nestbuis_bezoek %>%
  mutate(description = ifelse(observation_type == "versheid muizensporen", description,
                              ifelse(aantal  > 0, "aanwezig", "afwezig")),
         type = ifelse(observation_type == "versheid muizensporen", activiteit, levensstadium)) %>%
  ggplot(aes(x = type, fill = description)) +
  geom_bar() +
  facet_wrap(~soort_nl ) +
  coord_flip() +
  theme(legend.position = "bottom")
```

```{r, fig.width= 10, fig.cap= "Voorkomen per bezoek"}
hazelmuis_nestbuis_bezoek %>%
  mutate(description = ifelse(observation_type == "versheid muizensporen", description,
                              ifelse(aantal  > 0, "aanwezig", "afwezig")),
         type = ifelse(observation_type == "versheid muizensporen", activiteit, levensstadium)) %>%
  filter(description != "afwezig") %>%
  ggplot(aes(x = type, fill = description)) +
  geom_bar() +
  facet_wrap(~soort_nl, scales = "free" ) +
  coord_flip() +
  theme(legend.position = "bottom")
```
## Data aggregatie

Aggregatie van data:

+ aggregatie van levensstadia
+ aggregatie per nestbuis per jaar
+ aggregatie andere soorten

```{r}
hazelmuis_nestbuis_occurence <- hazelmuis_nestbuis_bezoek %>%
  mutate(jaar = year(datum),
         soort_nl = ifelse(str_detect(soort_nl, "Hazelmuis"), soort_nl, "andere_soorten")) %>%
  group_by(meetnet, locatie, sublocatie, jaar) %>%
  mutate(n_bezoeken = n_distinct(visit_id)) %>%
  ungroup() %>%
  group_by(meetnet, locatie, sublocatie, jaar, n_bezoeken, soort_nl, observation_type, activiteit) %>%
  summarise(aanwezig = sum(aantal) > 0,
            aanwezig_vers = "F" %in% code,
            aantal = sum(aantal)) %>%
  ungroup() %>%
  mutate(aanwezig_oud_onzeker = aanwezig & !aanwezig_vers,
         aanwezig = ifelse(activiteit == "in nestbuis", aanwezig, aanwezig_vers)) 

hazelmuis_sporen_occurence <- hazelmuis_nestbuis_bezoek %>%
  mutate(jaar = year(datum),
         soort_nl = ifelse(str_detect(soort_nl, "Hazelmuis"), soort_nl, "andere_soorten")) %>%
  group_by(meetnet, locatie, sublocatie, jaar) %>%
  mutate(n_bezoeken = n_distinct(visit_id)) %>%
  ungroup() %>%
  group_by(meetnet, locatie, sublocatie, jaar, n_bezoeken, soort_nl, observation_type) %>%
  summarise(aanwezig = sum(aantal) > 0,
            aanwezig_vers = "F" %in% code,
            aantal = sum(aantal)) %>%
  ungroup() %>%
  mutate(aanwezig_oud_onzeker = aanwezig & !aanwezig_vers,
         aanwezig = ifelse(observation_type == "exact aantal", aanwezig, aanwezig_vers),
         type = ifelse(observation_type == "exact aantal", "individuen", "sporen")) 

hazelmuis_sporen_occurence_wide <- hazelmuis_sporen_occurence %>%
  select(locatie, sublocatie, jaar, n_bezoeken, soort_nl, type, aanwezig) %>%
  pivot_wider(names_from = c("soort_nl", "type"),
              values_from = "aanwezig") 
 
hazelmuis_sporen_occurence_wide <- hazelmuis_sporen_occurence_wide %>%
  mutate(andere_soorten_sporen = ifelse(is.na(andere_soorten_sporen), FALSE, andere_soorten_sporen),
         andere_soorten_individuen = ifelse(is.na(andere_soorten_individuen), FALSE, andere_soorten_individuen))
  
```


```{r, fig.width= 10, fig.cap= "Voorkomen per nestbuis"}
hazelmuis_nestbuis_occurence %>%
  mutate(description = ifelse(activiteit == "in nestbuis", ifelse(aanwezig, "aanwezig", "afwezig"),
                              ifelse(aanwezig_vers, "aanwezig - vers",
                                     ifelse(aanwezig_oud_onzeker, "aanwezig - enkel oud of onzeker", "afwezig")))) %>%
  ggplot(aes(x = activiteit, fill = description)) +
  geom_bar() +
  facet_wrap(~soort_nl ) +
  coord_flip() +
  theme(legend.position = "bottom")
```
```{r, fig.cap= "Aantal bezoeken per nestbuis"}
hazelmuis_nestbuis_occurence %>%
  distinct(meetnet, locatie, sublocatie, jaar, n_bezoeken) %>%
  ggplot(aes(x = jaar, fill = factor(n_bezoeken))) +
  geom_bar()
```

```{r, fig.cap = "Invloed van aantal bezoeken op proportie aanwezigheid hazelmuisindividuen en sporen"}
hazelmuis_nestbuis_occurence %>%
  filter(soort_nl == "Hazelmuis") %>%
  group_by(soort_nl, n_bezoeken, activiteit) %>%
  summarise(prop_aanwezig = mean(aanwezig)) %>%
  ungroup() %>%
  ggplot(aes(x = n_bezoeken, y = prop_aanwezig)) +
  geom_point() +
  facet_wrap(~activiteit, scales = "free_y")
```


```{r}
hazelmuis_nestbuis_occurence %>%
  filter(activiteit %in% c("in nestbuis", "nest")) %>%
  mutate(description = ifelse(activiteit == "in nestbuis", ifelse(aanwezig, "aanwezig", "afwezig"),
                              ifelse(aanwezig_vers, "aanwezig - vers",
                                     ifelse(aanwezig_oud_onzeker, "aanwezig - enkel oud of onzeker", "afwezig")))) %>%
  ggplot(aes(x = jaar, fill = description)) +
  geom_bar() +
  facet_wrap(~ activiteit + soort_nl, scales = "free_y") +
  theme(legend.position = "bottom")
```

```{r}
hazelmuis_sporen_occurence_wide %>%
  ggplot(aes(x = Hazelmuis_individuen, y = andere_soorten_individuen)) +
  stat_sum()
```
```{r}
hazelmuis_sporen_occurence_wide %>%
  ggplot(aes(x = Hazelmuis_sporen, y = andere_soorten_sporen)) +
  stat_sum()
```
```{r}
cor(hazelmuis_sporen_occurence_wide$Hazelmuis_sporen, hazelmuis_sporen_occurence_wide$andere_soorten_sporen)
```
```{r}
cor(hazelmuis_sporen_occurence_wide$Hazelmuis_individuen, hazelmuis_sporen_occurence_wide$andere_soorten_individuen)
```

## Analyseset

+ minstens 3 bezoeken

```{r}
analyseset_nesten_jaar <- hazelmuis_nestbuis_occurence %>%
  filter(n_bezoeken > 2) %>%
  filter(soort_nl == "Hazelmuis") %>%
  filter(activiteit == "nest") %>%
  mutate(gebied = ifelse(!is.na(str_locate(locatie, "-")[, "start"]), 
                         str_sub(locatie, 1, end = str_locate(locatie, "-")[, "start"] - 2),
                         locatie),
         gebied = ifelse(gebied %in% c("Broekbos", "Konenbos"), "Broekbos - Konenbos",
                         ifelse(gebied %in% c("Teuvenerberg", "Obsinnich"), "Teuvenerberg - Obsinnisch", gebied)), 
         sublocatie = str_c(locatie, ": ", sublocatie),
         year_scaled = jaar - min(jaar) + 1,
         fjaar = factor(jaar),
         aanwezig = ifelse(aanwezig, 1, 0))

data_sim_year <- tibble(jaar = c(2020:2024),
                        fjaar = factor(jaar),
                         activiteit = "nest",
                         soort_nl = "Hazelmuis",
                         data_type = "sim_year")

data_sim_trend <- tibble(jaar = c(2020:2024),
                        year_scaled = c(1:5),
                         activiteit = "nest",
                         soort_nl = "Hazelmuis",
                         data_type = "sim_trend")

data_sim_locatie <- analyseset_nesten_jaar %>%
  distinct(gebied, locatie) %>%
  mutate(activiteit = "nest",
           soort_nl = "Hazelmuis",
           data_type = "sim_locatie")

data_sim_gebied_year <- analyseset_nesten_jaar %>%
  distinct(gebied, jaar, fjaar) %>%
  mutate(activiteit = "nest",
           soort_nl = "Hazelmuis",
           data_type = "sim_gebied")

data_sim_trend_gebied <- analyseset_nesten_jaar %>%
  distinct(gebied, jaar, year_scaled) %>%
  mutate(activiteit = "nest",
           soort_nl = "Hazelmuis",
           data_type = "sim_trend_gebied")

data_comb <- analyseset_nesten_jaar %>%
  mutate(data_type = "obs") %>%
  bind_rows(data_sim_year) %>%
  bind_rows(data_sim_locatie) %>%
  bind_rows(data_sim_gebied_year) %>%
  mutate(geb = str_sub(gebied, 1, 2))

data_comb_trend <- analyseset_nesten_jaar %>%
  mutate(data_type = "obs") %>%
  bind_rows(data_sim_trend) %>%
  bind_rows(data_sim_trend_gebied)
```


## Modelverkenning

### Nesten

```{r}
indexmodel_iid_0 <- inla(formula = aanwezig ~ 0 + fjaar +
                                f(sublocatie, 
                                  model = "iid", 
                                  hyper = list(theta = list(prior = "pc.prec", param = c(1, 0.05))))  + 
                                f(locatie,
                                  model = "iid", 
                                  hyper = list(theta = list(prior = "pc.prec", param = c(1, 0.05)))),
                       family = "binomial",
                       data = analyseset_nesten_jaar,
                       control.compute = list(config = TRUE, waic = TRUE),
                       control.predictor = list(compute = TRUE))

indexmodel_iid <- inla(formula = aanwezig ~ fjaar +
                                f(sublocatie, 
                                  model = "iid", 
                                  hyper = list(theta = list(prior = "pc.prec", param = c(1, 0.05))))  + 
                                f(locatie,
                                  model = "iid", 
                                  hyper = list(theta = list(prior = "pc.prec", param = c(1, 0.05)))),
                       family = "binomial",
                       data = data_comb,
                       control.compute = list(config = TRUE, waic = TRUE),
                       control.predictor = list(compute = TRUE),
                       quantiles = c(0.025, 0.05, 0.5, 0.95, 0.975))

indexmodel_gebied_iid <- inla(formula = aanwezig ~ fjaar*gebied +
                                f(sublocatie, 
                                  model = "iid", 
                                  hyper = list(theta = list(prior = "pc.prec", param = c(1, 0.05))))  + 
                                f(locatie,
                                  model = "iid", 
                                  hyper = list(theta = list(prior = "pc.prec", param = c(1, 0.05)))),
                       family = "binomial",
                       data = data_comb,
                       control.compute = list(config = TRUE, waic = TRUE),
                       control.predictor = list(compute = TRUE),
                       quantiles = c(0.025, 0.05, 0.5, 0.95, 0.975))

indexmodel_gebied_iid_0 <- inla(formula = aanwezig ~ 0 + fjaar*geb +
                                f(sublocatie, 
                                  model = "iid", 
                                  hyper = list(theta = list(prior = "pc.prec", param = c(1, 0.05))))  + 
                                f(locatie,
                                  model = "iid", 
                                  hyper = list(theta = list(prior = "pc.prec", param = c(1, 0.05)))),
                       family = "binomial",
                       data = data_comb,
                       control.compute = list(config = TRUE, waic = TRUE),
                       control.predictor = list(compute = TRUE),
                       quantiles = c(0.025, 0.05, 0.5, 0.95, 0.975))

trendmodel_iid <- inla(formula = aanwezig ~ year_scaled +
                                f(sublocatie, 
                                  model = "iid", 
                                  hyper = list(theta = list(prior = "pc.prec", param = c(1, 0.05))))  + 
                                f(locatie,
                                  model = "iid", 
                                  hyper = list(theta = list(prior = "pc.prec", param = c(1, 0.05)))),
                       family = "binomial",
                       data = data_comb_trend,
                       control.compute = list(config = TRUE, waic = TRUE),
                       control.predictor = list(compute = TRUE),
                       quantiles = c(0.025, 0.05, 0.5, 0.95, 0.975))

trendmodel_gebied_iid <- inla(formula = aanwezig ~ year_scaled*gebied +
                                f(sublocatie, 
                                  model = "iid", 
                                  hyper = list(theta = list(prior = "pc.prec", param = c(1, 0.05))))  + 
                                f(locatie,
                                  model = "iid", 
                                  hyper = list(theta = list(prior = "pc.prec", param = c(1, 0.05)))),
                       family = "binomial",
                       data = data_comb_trend,
                       control.compute = list(config = TRUE, waic = TRUE),
                       control.predictor = list(compute = TRUE),
                       quantiles = c(0.025, 0.05, 0.5, 0.95, 0.975))

trendmodel_iid$summary.fixed
```

```{r}
trend_prop_procentueel_1_2 <- (plogis(-1.067297114	- 2 * -0.001780439) - plogis(-1.067297114	- 1 * -0.001780439)) / plogis(-1.067297114	- 1 * -0.001780439) * 100

trend_prop_procentueel_2_3 <- (plogis(-1.067297114	- 3 * -0.001780439) - plogis(-1.067297114	- 2 * -0.001780439)) / plogis(-1.067297114	- 2 * -0.001780439) * 100

trend_prop_procentueel_3_4 <- (plogis(-1.067297114	- 4 * -0.001780439) - plogis(-1.067297114	- 3 * -0.001780439)) / plogis(-1.067297114	- 3 * -0.001780439) * 100

trend_prop_procentueel_1_4 <- (plogis(-1.067297114	- 4 * -0.001780439) - plogis(-1.067297114	- 1 * -0.001780439)) / plogis(-1.067297114	- 1 * -0.001780439) * 100/3
```


```{r}
indexmodel_gebied_iid_0$summary.fixed
```


```{r}
data_comb <- data_comb %>%
  mutate(mean = plogis(indexmodel_iid$summary.fitted.values$mean),
         lcl_0.90 = plogis(indexmodel_iid$summary.fitted.values$`0.05quant`),
         ucl_0.90 = plogis(indexmodel_iid$summary.fitted.values$`0.95quant`))
```


```{r, fig.height= 8}
data_comb %>%
  filter(data_type == "sim_locatie") %>%
  ggplot(aes(x = locatie, y = mean, ymin = lcl_0.90, ymax = ucl_0.90)) +
  geom_point() +
  geom_errorbar() +
  facet_wrap(~gebied, scales = "free_x") +
  theme(axis.text.x = element_text(angle = 45))
```

```{r}
data_comb_gebied <- data_comb %>%
  mutate(mean = plogis(indexmodel_gebied_iid$summary.fitted.values$mean),
         lcl_0.90 = plogis(indexmodel_gebied_iid$summary.fitted.values$`0.05quant`),
         ucl_0.90 = plogis(indexmodel_gebied_iid$summary.fitted.values$`0.95quant`))

data_comb_trend <- data_comb_trend %>%
  mutate(mean = plogis(trendmodel_iid$summary.fitted.values$mean),
         lcl_0.90 = plogis(trendmodel_iid$summary.fitted.values$`0.05quant`),
         ucl_0.90 = plogis(trendmodel_iid$summary.fitted.values$`0.95quant`))
```

```{r}
data_comb_trend %>%
  filter(data_type == "sim_trend") %>%
  ggplot(aes(x = jaar, y = mean, ymin = lcl_0.90, ymax = ucl_0.90)) +
  geom_line() +
  geom_ribbon(alpha = 0.3) +
  geom_point(data = data_comb %>%
               filter(data_type == "sim_year"), 
             aes(x = jaar, y = mean)) +
   geom_errorbar(data = data_comb %>%
               filter(data_type == "sim_year"), 
             aes(x = jaar, ymin = lcl_0.90, ymax = ucl_0.90)) +
  lims(y = c(0,NA))
```

```{r}
data_comb_trend_gebied <- data_comb_trend %>%
  mutate(mean = plogis(trendmodel_gebied_iid$summary.fitted.values$mean),
         lcl_0.90 = plogis(trendmodel_gebied_iid$summary.fitted.values$`0.05quant`),
         ucl_0.90 = plogis(trendmodel_gebied_iid$summary.fitted.values$`0.95quant`))
```

```{r}
data_comb_trend_gebied %>%
  filter(data_type == "sim_trend_gebied") %>%
  ggplot(aes(x = jaar, y = mean, ymin = lcl_0.90, ymax = ucl_0.90)) +
  geom_line(colour = "grey") +
  geom_ribbon(alpha = 0.3, colour = "grey") +
  geom_point(data = data_comb_gebied %>%
               filter(data_type == "sim_gebied"), 
             aes(x = jaar, y = mean),
             size = 5, alpha = 0.6) +
   geom_errorbar(data = data_comb_gebied %>%
               filter(data_type == "sim_gebied"), 
             aes(x = jaar, ymin = lcl_0.90, ymax = ucl_0.90),
             width = 0, size = 10, alpha = 0.3) +
  facet_wrap(~gebied)

```

```{r}

data_comb_gebied %>%
  filter(data_type == "sim_gebied") %>%
  ggplot(aes(x = jaar, y = mean, ymin = lcl_0.90, ymax = ucl_0.90)) +
  geom_point(size = 3, alpha = 0.6) +
   geom_errorbar(width = 0, size = 10, alpha = 0.3) +
  facet_wrap(~gebied) +
  labs(x = "Jaar", y = "Proportie nesten hazelmuis") +
  lims(y = c(0, NA))

```

```{r}


  fun = function(...) {
    c(plogis(fjaar2020), plogis(fjaar2021), plogis(fjaar2022), plogis(fjaar2023), plogis(fjaar2024),
      (plogis(fjaar2021) - plogis(fjaar2020)) / plogis(fjaar2020),
      (plogis(fjaar2022) - plogis(fjaar2020)) / plogis(fjaar2020),
      (plogis(fjaar2023) - plogis(fjaar2020)) / plogis(fjaar2020),
      (plogis(fjaar2024) - plogis(fjaar2020)) / plogis(fjaar2020),
      (plogis(fjaar2022) - plogis(fjaar2021)) / plogis(fjaar2021),
      (plogis(fjaar2023) - plogis(fjaar2022)) / plogis(fjaar2022),
      (plogis(fjaar2024) - plogis(fjaar2023)) / plogis(fjaar2023))
      }

  model_inla.samples <- inla.posterior.sample(1000, indexmodel_iid_0)
  
  quantile_values <- c(0.025, 0.05, 0.20, 0.35,  0.65, 0.80, 0.95, 0.975)
  
  results_index <- inla.posterior.sample.eval(fun, model_inla.samples) %>%
    as.data.frame() %>%
    mutate(jaar = c(2020:2024, 2021:2024, 2022, 2023, 2024),
           jaar_ref = c(NA, NA, NA, NA, NA, 2020, 2020, 2020, 2020:2023)) %>%
    gather(starts_with("sample"), key = "sample", value = "waarde") %>%
    group_by(jaar, jaar_ref) %>%
    mutate(mean = mean(waarde),
           sd = sd(waarde)) %>%
    ungroup() %>%
    group_by(jaar, jaar_ref, mean, sd) %>%
    summarise(qs = quantile(waarde, quantile_values), prob = quantile_values) %>%
    ungroup() %>%
    mutate(l_u = ifelse(prob < 0.5, "lcl", "ucl"),
           ci = ifelse(prob %in% c(0.025, 0.975), "0.95",
                       ifelse(prob %in% c(0.05, 0.95), "0.90",
                              ifelse(prob %in% c(0.20, 0.80), "0.60",
                                     ifelse(prob %in% c(0.35, 0.65), "0.30", NA)))),
           type = str_c(l_u, "_", ci)) %>%
    select(-prob, -l_u, -ci) %>%
    spread(key = type, value = qs) %>%
    mutate(klasse = classification(lcl_0.90, ucl_0.90, threshold = c(-0.25, 0.33), reference = 0),
           klasse = ifelse(is.na(jaar_ref), NA, 
                           format(klasse, type = "markdown"))) %>%
    select(jaar, jaar_ref, mean, lcl_0.90, ucl_0.90, klasse)
  
  
```

```{r}
results_index %>%
  filter(is.na(jaar_ref)) %>%
  ggplot(aes(x = jaar, y = mean, ymin = lcl_0.90, ymax = ucl_0.90)) +
  geom_errorbar(width = 0, size = 10, alpha = 0.3) +
  geom_point(size = 3, alpha = 0.6) +
  labs(x = "Jaar", y = "Proportie nesten hazelmuis") +
  lims(y = c(0, NA))
```

```{r}
results_index_diff_ref <- results_index %>%
  filter(jaar_ref == 2020) %>%
  add_row(tibble(jaar = 2020,
                 jaar_ref = 2020,
                 mean = 0,
                 klasse = "R")) %>%
  mutate(klasse = as.character(klasse),
         klasse = str_remove_all(klasse, "`")) %>%
  mutate(mean_log = log(mean + 1),
          lcl_0.90_log = log(lcl_0.90 +1),
         ucl_0.90_log = log(ucl_0.90 +1) )

```


```{r}
c(rev(traffic_palette(7)), "grey65", "grey35", "grey50") %>%
  setNames(
    c("++", "+", "+~", "~", "-~", "-", "--", "?+", "?-", "?")
  ) -> klasse_color
klasse_color[4] <- inbo_steun_blauw

breaks_log <- log(c(0.01, 0.1, 0.25, 0.5, 0.75, 1, 1.33, 2, 3, 6))
labels_show <- str_c(c(-99, -90, -75, -50, -25, 0, 33, 100, 200, 500), " %")

results_index_diff_ref %>%
  ggplot(aes(x = jaar, y = mean_log, ymin = lcl_0.90_log, ymax = ucl_0.90_log, label = klasse, colour = klasse)) +
  geom_errorbar(width = 0, size = 10, alpha = 0.3) +
  geom_point(size = 7, alpha = 0.6) +
  geom_hline(yintercept = 0, linetype = 2) +
  geom_hline(yintercept = log(0.75), linetype = 3) +
  geom_hline(yintercept = log(1.33), linetype = 3) +
  geom_text(size = 4, colour = "black") +
  labs(y = "Verschil t.o.v. referentiejaar", x = "Jaar") +
  scale_y_continuous(breaks = breaks_log, labels = labels_show) +
  scale_color_manual(values = klasse_color) +
  theme(legend.position = "hide")
```
```{r}
results_index_diff_prevyear <- results_index %>%
  filter(jaar - jaar_ref == 1 ) %>%
  mutate(klasse = as.character(klasse),
         klasse = str_remove_all(klasse, "`")) %>%
  mutate(mean_log = log(mean + 1),
          lcl_0.90_log = log(lcl_0.90 +1),
         ucl_0.90_log = log(ucl_0.90 +1) ) %>%
  mutate(diff = str_c(jaar_ref, "-", jaar))
```

```{r}

results_index_diff_prevyear %>%
  ggplot(aes(x = diff, y = mean_log, ymin = lcl_0.90_log, ymax = ucl_0.90_log, label = klasse, colour = klasse)) +
  geom_errorbar(width = 0, size = 10, alpha = 0.3) +
  geom_point(size = 7, alpha = 0.6) +
  geom_hline(yintercept = 0, linetype = 2) +
  geom_hline(yintercept = log(0.75), linetype = 3) +
  geom_hline(yintercept = log(1.33), linetype = 3) +
  geom_text(size = 4, colour = "black") +
  labs(y = "Verschil opeenvolgende jaren", x = "Periode") +
  scale_y_continuous(breaks = breaks_log, labels = labels_show) +
  scale_color_manual(values = klasse_color) +
  theme(legend.position = "hide")
```

```{r}

  fun2 = function(...) {
    c(plogis((fjaar2020)), plogis(fjaar2021 ), plogis(fjaar2022), plogis(fjaar2023), plogis(fjaar2024),
            (plogis(fjaar2021) - plogis(fjaar2020)) / plogis(fjaar2020),
      (plogis(fjaar2022) - plogis(fjaar2020)) / plogis(fjaar2020),
      (plogis(fjaar2023) - plogis(fjaar2020)) / plogis(fjaar2020),
      (plogis(fjaar2024) - plogis(fjaar2020)) / plogis(fjaar2020),
      (plogis(fjaar2022) - plogis(fjaar2021)) / plogis(fjaar2021),
      (plogis(fjaar2023) - plogis(fjaar2022)) / plogis(fjaar2022),
      (plogis(fjaar2024) - plogis(fjaar2023)) / plogis(fjaar2023),
      plogis(fjaar2020 + gebTe), 
      plogis(fjaar2021 + gebTe + `fjaar2021:gebTe`), 
      plogis(fjaar2022 + gebTe + `fjaar2022:gebTe`), 
      plogis(fjaar2023 + gebTe + `fjaar2023:gebTe`), 
       plogis(fjaar2024 + gebTe + `fjaar2024:gebTe`), 
      (plogis(fjaar2021 + gebTe + `fjaar2021:gebTe`) - plogis(fjaar2020 + gebTe)) / plogis(fjaar2020 + gebTe), 
      (plogis(fjaar2022 + gebTe + `fjaar2022:gebTe`) - plogis(fjaar2020 + gebTe)) / plogis(fjaar2020 + gebTe), 
      (plogis(fjaar2023 + gebTe + `fjaar2023:gebTe`) - plogis(fjaar2020 + gebTe)) / plogis(fjaar2020 + gebTe),
      (plogis(fjaar2024 + gebTe + `fjaar2024:gebTe`) - plogis(fjaar2020 + gebTe)) / plogis(fjaar2020 + gebTe), 
      (plogis(fjaar2022 + gebTe + `fjaar2022:gebTe`) - plogis(fjaar2021 + gebTe + `fjaar2021:gebTe`)) / plogis(fjaar2021 + gebTe + `fjaar2021:gebTe`),
      (plogis(fjaar2023 + gebTe + `fjaar2023:gebTe`) - plogis(fjaar2022 + gebTe + `fjaar2022:gebTe`)) / plogis(fjaar2022 + gebTe + `fjaar2022:gebTe`),
      (plogis(fjaar2024 + gebTe + `fjaar2024:gebTe`) - plogis(fjaar2023 + gebTe + `fjaar2023:gebTe`)) / plogis(fjaar2023 + gebTe + `fjaar2023:gebTe`),
       plogis(fjaar2020 + gebVe), 
      plogis(fjaar2021 + gebVe + `fjaar2021:gebVe`), 
      plogis(fjaar2022 + gebVe + `fjaar2022:gebVe`), 
      plogis(fjaar2023 + gebVe + `fjaar2023:gebVe`), 
       plogis(fjaar2024 + gebVe + `fjaar2024:gebVe`), 
      (plogis(fjaar2021 + gebVe + `fjaar2021:gebVe`) - plogis(fjaar2020 + gebVe)) / plogis(fjaar2020 + gebVe), 
      (plogis(fjaar2022 + gebVe + `fjaar2022:gebVe`) - plogis(fjaar2020 + gebVe)) / plogis(fjaar2020 + gebVe), 
      (plogis(fjaar2023 + gebVe + `fjaar2023:gebVe`) - plogis(fjaar2020 + gebVe)) / plogis(fjaar2020 + gebVe),
      (plogis(fjaar2024 + gebVe + `fjaar2024:gebVe`) - plogis(fjaar2020 + gebVe)) / plogis(fjaar2020 + gebVe), 
      (plogis(fjaar2022 + gebVe + `fjaar2022:gebVe`) - plogis(fjaar2021 + gebVe + `fjaar2021:gebVe`)) / plogis(fjaar2021 + gebVe + `fjaar2021:gebVe`),
      (plogis(fjaar2023 + gebVe + `fjaar2023:gebVe`) - plogis(fjaar2022 + gebVe + `fjaar2022:gebVe`)) / plogis(fjaar2022 + gebVe + `fjaar2022:gebVe`),
      (plogis(fjaar2024 + gebVe + `fjaar2024:gebVe`) - plogis(fjaar2023 + gebVe + `fjaar2023:gebVe`)) / plogis(fjaar2023 + gebVe + `fjaar2023:gebVe`),
       plogis(fjaar2020 + gebVr), 
      plogis(fjaar2021 + gebVr + `fjaar2021:gebVr`), 
      plogis(fjaar2022 + gebVr + `fjaar2022:gebVr`), 
      plogis(fjaar2023 + gebVr + `fjaar2023:gebVr`), 
       plogis(fjaar2024 + gebVr + `fjaar2024:gebVr`), 
      (plogis(fjaar2021 + gebVr + `fjaar2021:gebVr`) - plogis(fjaar2020 + gebVr)) / plogis(fjaar2020 + gebVr), 
      (plogis(fjaar2022 + gebVr + `fjaar2022:gebVr`) - plogis(fjaar2020 + gebVr)) / plogis(fjaar2020 + gebVr), 
      (plogis(fjaar2023 + gebVr + `fjaar2023:gebVr`) - plogis(fjaar2020 + gebVr)) / plogis(fjaar2020 + gebVr),
      (plogis(fjaar2024 + gebVr + `fjaar2024:gebVr`) - plogis(fjaar2020 + gebVr)) / plogis(fjaar2020 + gebVr), 
      (plogis(fjaar2022 + gebVr + `fjaar2022:gebVr`) - plogis(fjaar2021 + gebVr + `fjaar2021:gebVr`)) / plogis(fjaar2021 + gebVr + `fjaar2021:gebVr`),
      (plogis(fjaar2023 + gebVr + `fjaar2023:gebVr`) - plogis(fjaar2022 + gebVr + `fjaar2022:gebVr`)) / plogis(fjaar2022 + gebVr + `fjaar2022:gebVr`),
      (plogis(fjaar2024 + gebVr + `fjaar2024:gebVr`) - plogis(fjaar2023 + gebVr + `fjaar2023:gebVr`)) / plogis(fjaar2023 + gebVr + `fjaar2023:gebVr`))
      }

  model_inla.samples <- inla.posterior.sample(1000, indexmodel_gebied_iid_0)
  
  quantile_values <- c(0.05, 0.95)
  
  results_index_geb <- inla.posterior.sample.eval(fun2, model_inla.samples) %>%
    as.data.frame() %>%
    mutate(geb = c(rep("Broekbos - Konenbos", 12), 
                   rep("Teuvenerberg - Obsinnisch", 12), 
                   rep("Veursbos", 12), 
                   rep("Vrouwenbos", 12)),
           jaar = rep(c(2020:2024, 2021:2024, 2022, 2023, 2024), 4),
           jaar_ref = rep(c(NA, NA, NA, NA, NA, 2020, 2020, 2020, 2020:2023), 4)) %>%
    gather(starts_with("sample"), key = "sample", value = "waarde") %>%
    group_by(geb, jaar, jaar_ref) %>%
    mutate(mean = mean(waarde),
           sd = sd(waarde)) %>%
    ungroup() %>%
    group_by(geb, jaar, jaar_ref, mean, sd) %>%
    summarise(qs = quantile(waarde, quantile_values), prob = quantile_values) %>%
    ungroup() %>%
    mutate(l_u = ifelse(prob < 0.5, "lcl", "ucl"),
           ci = ifelse(prob %in% c(0.025, 0.975), "0.95",
                       ifelse(prob %in% c(0.05, 0.95), "0.90",
                              ifelse(prob %in% c(0.20, 0.80), "0.60",
                                     ifelse(prob %in% c(0.35, 0.65), "0.30", NA)))),
           type = str_c(l_u, "_", ci)) %>%
    select(-prob, -l_u, -ci) %>%
    spread(key = type, value = qs) %>%
    mutate(klasse = classification(lcl_0.90, ucl_0.90, threshold = c(-0.25, 0.33), reference = 0),
           klasse = ifelse(is.na(jaar_ref), NA, 
                           format(klasse, type = "markdown"))) %>%
    select(geb, jaar, jaar_ref, mean, lcl_0.90, ucl_0.90, klasse)
  
  
```

```{r, fig.height= 6, fig.width = 6}
results_index_geb %>%
  filter(is.na(jaar_ref)) %>%
  ggplot(aes(x = jaar, y = mean, ymin = lcl_0.90, ymax = ucl_0.90)) +
  geom_errorbar(width = 0, size = 10, alpha = 0.3) +
  geom_point(size = 3, alpha = 0.6) +
  labs(x = "Jaar", y = "Proportie nesten hazelmuis") +
  lims(y = c(0, NA)) +
  facet_wrap(~geb)
```

```{r, fig.height= 6, fig.width = 6}
results_index_geb %>%
  filter(is.na(jaar_ref)) %>%
  ggplot(aes(x = str_sub(geb, 1, 2), y = mean, ymin = lcl_0.90, ymax = ucl_0.90)) +
  geom_errorbar(width = 0, size = 10, alpha = 0.3) +
  geom_point(size = 3, alpha = 0.6) +
  labs(x = "Gebied", y = "Proportie nesten hazelmuis") +
  lims(y = c(0, NA)) +
  facet_wrap(~jaar)
```

```{r}
results_index_diff_ref_geb <- results_index_geb %>%
  filter(jaar_ref == 2020) %>%
  add_row(tibble(jaar = 2020,
                 jaar_ref = 2020,
                 geb = unique(results_index_geb$geb),
                 mean = 0,
                 klasse = "R")) %>%
  mutate(klasse = as.character(klasse),
         klasse = str_remove_all(klasse, "`")) %>%
  mutate(mean_log = log(mean + 1),
          lcl_0.90_log = log(lcl_0.90 +1),
         ucl_0.90_log = log(ucl_0.90 +1) )

```


```{r, fig.height= 6, fig.width = 6}

results_index_diff_ref_geb %>%
  ggplot(aes(x = jaar, y = mean_log, ymin = lcl_0.90_log, ymax = ucl_0.90_log, label = klasse, colour = klasse)) +
  geom_errorbar(width = 0, size = 10, alpha = 0.3) +
  geom_point(size = 7, alpha = 0.6) +
  geom_hline(yintercept = 0, linetype = 2) +
  geom_hline(yintercept = log(0.75), linetype = 3) +
  geom_hline(yintercept = log(1.33), linetype = 3) +
  geom_text(size = 4, colour = "black") +
  labs(y = "Verschil t.o.v. referentiejaar", x = "Jaar") +
  scale_y_continuous(breaks = breaks_log, labels = labels_show) +
  scale_color_manual(values = klasse_color) +
  theme(legend.position = "hide") +
  facet_wrap(~geb)
```

```{r}
results_index_diff_prevyear_geb <- results_index_geb %>%
  filter(jaar - jaar_ref == 1 ) %>%
  mutate(klasse = as.character(klasse),
         klasse = str_remove_all(klasse, "`")) %>%
  mutate(mean_log = log(mean + 1),
          lcl_0.90_log = log(lcl_0.90 +1),
         ucl_0.90_log = log(ucl_0.90 +1) ) %>%
  mutate(diff = str_c(jaar_ref, "-", jaar))
```

```{r, fig.height= 6, fig.width = 6}

results_index_diff_prevyear_geb %>%
  ggplot(aes(x = diff, y = mean_log, ymin = lcl_0.90_log, ymax = ucl_0.90_log, label = klasse, colour = klasse)) +
  geom_errorbar(width = 0, size = 10, alpha = 0.3) +
  geom_point(size = 7, alpha = 0.6) +
  geom_hline(yintercept = 0, linetype = 2) +
  geom_hline(yintercept = log(0.75), linetype = 3) +
  geom_hline(yintercept = log(1.33), linetype = 3) +
  geom_text(size = 4, colour = "black") +
  labs(y = "Verschil opeenvolgende jaren", x = "Periode") +
  scale_y_continuous(breaks = breaks_log, labels = labels_show) +
  scale_color_manual(values = klasse_color) +
  theme(legend.position = "hide") +
  facet_wrap(~geb)
```
### Individuen

```{r}
analyseset_individuen_jaar <- hazelmuis_nestbuis_occurence %>%
  filter(n_bezoeken > 2) %>%
  filter(soort_nl == "Hazelmuis") %>%
  filter(activiteit == "in nestbuis") %>%
  mutate(gebied = ifelse(!is.na(str_locate(locatie, "-")[, "start"]), 
                         str_sub(locatie, 1, end = str_locate(locatie, "-")[, "start"] - 2),
                         locatie),
         gebied = ifelse(gebied %in% c("Broekbos", "Konenbos"), "Broekbos - Konenbos",
                         ifelse(gebied %in% c("Teuvenerberg", "Obsinnich"), "Teuvenerberg - Obsinnisch", gebied)), 
         sublocatie = str_c(locatie, ": ", sublocatie),
         year_scaled = jaar - min(jaar) + 1,
         fjaar = factor(jaar),
         aanwezig = ifelse(aanwezig, 1, 0),
         geb = str_sub(gebied, 1, 2))

```

```{r}
indexmodel_individu_iid_0 <- inla(formula = aanwezig ~ 0 + fjaar +
                                f(sublocatie, 
                                  model = "iid", 
                                  hyper = list(theta = list(prior = "pc.prec", param = c(1, 0.05))))  + 
                                f(locatie,
                                  model = "iid", 
                                  hyper = list(theta = list(prior = "pc.prec", param = c(1, 0.05)))),
                       family = "binomial",
                       data = analyseset_individuen_jaar,
                       control.compute = list(config = TRUE, waic = TRUE),
                       control.predictor = list(compute = TRUE))

indexmodel_individu_gebied_iid_0 <- inla(formula = aanwezig ~ 0 + fjaar*geb +
                                f(sublocatie, 
                                  model = "iid", 
                                  hyper = list(theta = list(prior = "pc.prec", param = c(1, 0.05))))  + 
                                f(locatie,
                                  model = "iid", 
                                  hyper = list(theta = list(prior = "pc.prec", param = c(1, 0.05)))),
                       family = "binomial",
                       data = analyseset_individuen_jaar,
                       control.compute = list(config = TRUE, waic = TRUE),
                       control.predictor = list(compute = TRUE),
                       quantiles = c(0.025, 0.05, 0.5, 0.95, 0.975))
```

```{r}
  model_inla.samples <- inla.posterior.sample(1000, indexmodel_individu_iid_0)
  
  quantile_values <- c(0.025, 0.05, 0.20, 0.35,  0.65, 0.80, 0.95, 0.975)
  
  results_index_individu <- inla.posterior.sample.eval(fun, model_inla.samples) %>%
    as.data.frame() %>%
    mutate(jaar = c(2020:2024, 2021:2024, 2022, 2023, 2024),
           jaar_ref = c(NA, NA, NA, NA, NA, 2020, 2020, 2020, 2020:2023)) %>%
    gather(starts_with("sample"), key = "sample", value = "waarde") %>%
    group_by(jaar, jaar_ref) %>%
    mutate(mean = mean(waarde),
           sd = sd(waarde)) %>%
    ungroup() %>%
    group_by(jaar, jaar_ref, mean, sd) %>%
    summarise(qs = quantile(waarde, quantile_values), prob = quantile_values) %>%
    ungroup() %>%
    mutate(l_u = ifelse(prob < 0.5, "lcl", "ucl"),
           ci = ifelse(prob %in% c(0.025, 0.975), "0.95",
                       ifelse(prob %in% c(0.05, 0.95), "0.90",
                              ifelse(prob %in% c(0.20, 0.80), "0.60",
                                     ifelse(prob %in% c(0.35, 0.65), "0.30", NA)))),
           type = str_c(l_u, "_", ci)) %>%
    select(-prob, -l_u, -ci) %>%
    spread(key = type, value = qs) %>%
    mutate(klasse = classification(lcl_0.90, ucl_0.90, threshold = c(-0.25, 0.33), reference = 0),
           klasse = ifelse(is.na(jaar_ref), NA, 
                           format(klasse, type = "markdown"))) %>%
    select(jaar, jaar_ref, mean, lcl_0.90, ucl_0.90, klasse)
  
  
    model_inla.samples <- inla.posterior.sample(1000, indexmodel_individu_gebied_iid_0)
  
  quantile_values <- c(0.05, 0.95)
  
  results_index_individu_geb <- inla.posterior.sample.eval(fun2, model_inla.samples) %>%
    as.data.frame() %>%
    mutate(geb = c(rep("Broekbos - Konenbos", 12), 
                   rep("Teuvenerberg - Obsinnisch", 12), 
                   rep("Veursbos", 12), 
                   rep("Vrouwenbos", 12)),
           jaar = rep(c(2020:2024, 2021:2024, 2022, 2023, 2024), 4),
           jaar_ref = rep(c(NA, NA, NA, NA, NA, 2020, 2020, 2020, 2020:2023), 4)) %>%
    gather(starts_with("sample"), key = "sample", value = "waarde") %>%
    group_by(geb, jaar, jaar_ref) %>%
    mutate(mean = mean(waarde),
           sd = sd(waarde)) %>%
    ungroup() %>%
    group_by(geb, jaar, jaar_ref, mean, sd) %>%
    summarise(qs = quantile(waarde, quantile_values), prob = quantile_values) %>%
    ungroup() %>%
    mutate(l_u = ifelse(prob < 0.5, "lcl", "ucl"),
           ci = ifelse(prob %in% c(0.025, 0.975), "0.95",
                       ifelse(prob %in% c(0.05, 0.95), "0.90",
                              ifelse(prob %in% c(0.20, 0.80), "0.60",
                                     ifelse(prob %in% c(0.35, 0.65), "0.30", NA)))),
           type = str_c(l_u, "_", ci)) %>%
    select(-prob, -l_u, -ci) %>%
    spread(key = type, value = qs) %>%
    mutate(klasse = classification(lcl_0.90, ucl_0.90, threshold = c(-0.25, 0.33), reference = 0),
           klasse = ifelse(is.na(jaar_ref), NA, 
                           format(klasse, type = "markdown"))) %>%
    select(geb, jaar, jaar_ref, mean, lcl_0.90, ucl_0.90, klasse)
```
```{r}
results_index_individu %>%
  filter(is.na(jaar_ref)) %>%
  ggplot(aes(x = jaar, y = mean, ymin = lcl_0.90, ymax = ucl_0.90)) +
  geom_errorbar(width = 0, size = 10, alpha = 0.3) +
  geom_point(size = 3, alpha = 0.6) +
  labs(x = "Jaar", y = "Proportie individuen hazelmuis") +
  lims(y = c(0, NA))
```

```{r}
results_index_individu_diff_ref <- results_index_individu %>%
  filter(jaar_ref == 2020) %>%
  add_row(tibble(jaar = 2020,
                 jaar_ref = 2020,
                 mean = 0,
                 klasse = "R")) %>%
  mutate(klasse = as.character(klasse),
         klasse = str_remove_all(klasse, "`")) %>%
  mutate(mean_log = log(mean + 1),
          lcl_0.90_log = log(lcl_0.90 +1),
         ucl_0.90_log = log(ucl_0.90 +1) )

```


```{r}

results_index_individu_diff_ref %>%
  ggplot(aes(x = jaar, y = mean_log, ymin = lcl_0.90_log, ymax = ucl_0.90_log, label = klasse, colour = klasse)) +
  geom_errorbar(width = 0, size = 10, alpha = 0.3) +
  geom_point(size = 7, alpha = 0.6) +
  geom_hline(yintercept = 0, linetype = 2) +
  geom_hline(yintercept = log(0.75), linetype = 3) +
  geom_hline(yintercept = log(1.33), linetype = 3) +
  geom_text(size = 4, colour = "black") +
  labs(y = "Verschil t.o.v. referentiejaar", x = "Jaar") +
  scale_y_continuous(breaks = breaks_log, labels = labels_show) +
  scale_color_manual(values = klasse_color) +
  theme(legend.position = "hide")
```

```{r}
results_index_individu_diff_prevyear <- results_index_individu %>%
  filter(jaar - jaar_ref == 1 ) %>%
  mutate(klasse = as.character(klasse),
         klasse = str_remove_all(klasse, "`")) %>%
  mutate(mean_log = log(mean + 1),
          lcl_0.90_log = log(lcl_0.90 +1),
         ucl_0.90_log = log(ucl_0.90 +1) ) %>%
  mutate(diff = str_c(jaar_ref, "-", jaar))
```

```{r}

results_index_individu_diff_prevyear %>%
  ggplot(aes(x = diff, y = mean_log, ymin = lcl_0.90_log, ymax = ucl_0.90_log, label = klasse, colour = klasse)) +
  geom_errorbar(width = 0, size = 10, alpha = 0.3) +
  geom_point(size = 7, alpha = 0.6) +
  geom_hline(yintercept = 0, linetype = 2) +
  geom_hline(yintercept = log(0.75), linetype = 3) +
  geom_hline(yintercept = log(1.33), linetype = 3) +
  geom_text(size = 4, colour = "black") +
  labs(y = "Verschil opeenvolgende jaren", x = "Periode") +
  scale_y_continuous(breaks = breaks_log, labels = labels_show) +
  scale_color_manual(values = klasse_color) +
  theme(legend.position = "hide")
```
```{r, fig.height= 6, fig.width = 6}
results_index_individu_geb %>%
  filter(is.na(jaar_ref)) %>%
  ggplot(aes(x = jaar, y = mean, ymin = lcl_0.90, ymax = ucl_0.90)) +
  geom_errorbar(width = 0, size = 10, alpha = 0.3) +
  geom_point(size = 3, alpha = 0.6) +
  labs(x = "Jaar", y = "Proportie individuen hazelmuis") +
  lims(y = c(0, NA)) +
  facet_wrap(~geb)
```

```{r, fig.height= 6, fig.width = 6}
results_index_individu_geb %>%
  filter(is.na(jaar_ref)) %>%
  ggplot(aes(x = str_sub(geb, 1, 2), y = mean, ymin = lcl_0.90, ymax = ucl_0.90)) +
  geom_errorbar(width = 0, size = 10, alpha = 0.3) +
  geom_point(size = 3, alpha = 0.6) +
  labs(x = "Gebied", y = "Proportie individuen hazelmuis") +
  lims(y = c(0, NA)) +
  facet_wrap(~jaar)
```

```{r}
results_index_individu_diff_ref_geb <- results_index_individu_geb %>%
  filter(jaar_ref == 2020) %>%
  add_row(tibble(jaar = 2020,
                 jaar_ref = 2020,
                 geb = unique(results_index_geb$geb),
                 mean = 0,
                 klasse = "R")) %>%
  mutate(klasse = as.character(klasse),
         klasse = str_remove_all(klasse, "`")) %>%
  mutate(mean_log = log(mean + 1),
          lcl_0.90_log = log(lcl_0.90 +1),
         ucl_0.90_log = log(ucl_0.90 +1) )

```


```{r, fig.height= 6, fig.width = 6}

results_index_individu_diff_ref_geb %>%
  ggplot(aes(x = jaar, y = mean_log, ymin = lcl_0.90_log, ymax = ucl_0.90_log, label = klasse, colour = klasse)) +
  geom_errorbar(width = 0, size = 10, alpha = 0.3) +
  geom_point(size = 7, alpha = 0.6) +
  geom_hline(yintercept = 0, linetype = 2) +
  geom_hline(yintercept = log(0.75), linetype = 3) +
  geom_hline(yintercept = log(1.33), linetype = 3) +
  geom_text(size = 4, colour = "black") +
  labs(y = "Verschil t.o.v. referentiejaar", x = "Jaar") +
  scale_y_continuous(breaks = breaks_log, labels = labels_show) +
  scale_color_manual(values = klasse_color) +
  theme(legend.position = "hide") +
  facet_wrap(~geb)
```

```{r}
results_index_individu_diff_prevyear_geb <- results_index_individu_geb %>%
  filter(jaar - jaar_ref == 1 ) %>%
  mutate(klasse = as.character(klasse),
         klasse = str_remove_all(klasse, "`")) %>%
  mutate(mean_log = log(mean + 1),
          lcl_0.90_log = log(lcl_0.90 +1),
         ucl_0.90_log = log(ucl_0.90 +1) ) %>%
  mutate(diff = str_c(jaar_ref, "-", jaar))
```

```{r, fig.height= 6, fig.width = 6}

results_index_individu_diff_prevyear_geb %>%
  ggplot(aes(x = diff, y = mean_log, ymin = lcl_0.90_log, ymax = ucl_0.90_log, label = klasse, colour = klasse)) +
  geom_errorbar(width = 0, size = 10, alpha = 0.3) +
  geom_point(size = 7, alpha = 0.6) +
  geom_hline(yintercept = 0, linetype = 2) +
  geom_hline(yintercept = log(0.75), linetype = 3) +
  geom_hline(yintercept = log(1.33), linetype = 3) +
  geom_text(size = 4, colour = "black") +
  labs(y = "Verschil opeenvolgende jaren", x = "Periode") +
  scale_y_continuous(breaks = breaks_log, labels = labels_show) +
  scale_color_manual(values = klasse_color) +
  theme(legend.position = "hide") +
  facet_wrap(~geb)
```

```{r}
bind_rows(
  results_index %>%
    mutate(type = "nesten"),
  results_index_individu %>%
    mutate(type = "individuen")
) %>% 
  filter(is.na(jaar_ref)) %>%
  ggplot(aes(x = jaar, y = mean, ymin = lcl_0.90, ymax = ucl_0.90)) +
  geom_errorbar(width = 0, size = 10, alpha = 0.3) +
  geom_point(size = 3, alpha = 0.6) +
  labs(x = "Jaar", y = "Proportie bezette nestbuizen") +
  lims(y = c(0, NA)) +
  facet_wrap(~type)
```
```{r}
bind_rows(
  results_index_diff_ref %>%
    mutate(type = "nesten"),
  results_index_individu_diff_ref %>%
    mutate(type = "individuen")
) %>% 
  ggplot(aes(x = jaar, y = mean_log, ymin = lcl_0.90_log, ymax = ucl_0.90_log, label = klasse, colour = klasse)) +
  geom_errorbar(width = 0, size = 10, alpha = 0.3) +
  geom_point(size = 7, alpha = 0.6) +
  geom_hline(yintercept = 0, linetype = 2) +
  geom_hline(yintercept = log(0.75), linetype = 3) +
  geom_hline(yintercept = log(1.33), linetype = 3) +
  geom_text(size = 4, colour = "black") +
  labs(y = "Verschil t.o.v. referentiejaar", x = "Jaar") +
  scale_y_continuous(breaks = breaks_log, labels = labels_show) +
  scale_color_manual(values = klasse_color) +
  theme(legend.position = "hide") +
  facet_wrap(~type)
```
```{r}
bind_rows(
  results_index_diff_prevyear %>%
    mutate(type = "nesten"),
  results_index_individu_diff_prevyear %>%
    mutate(type = "individuen")
) %>% 
  mutate(periode = str_c(jaar_ref, "-", jaar)) %>%
  ggplot(aes(x = periode, y = mean_log, ymin = lcl_0.90_log, ymax = ucl_0.90_log, label = klasse, colour = klasse)) +
  geom_errorbar(width = 0, size = 10, alpha = 0.3) +
  geom_point(size = 7, alpha = 0.6) +
  geom_hline(yintercept = 0, linetype = 2) +
  geom_hline(yintercept = log(0.75), linetype = 3) +
  geom_hline(yintercept = log(1.33), linetype = 3) +
  geom_text(size = 4, colour = "black") +
  labs(y = "Verschil opeenvolgende jaren", x = "Periode") +
  scale_y_continuous(breaks = breaks_log, labels = labels_show) +
  scale_color_manual(values = klasse_color) +
  theme(legend.position = "hide") +
  facet_wrap(~type)
```
```{r, fig.height= 8, fig.width= 7}
bind_rows(
  results_index_geb %>%
    mutate(type = "nesten"),
  results_index_individu_geb %>%
    mutate(type = "individuen")
) %>% 
  filter(is.na(jaar_ref)) %>%
  ggplot(aes(x = jaar, y = mean, ymin = lcl_0.90, ymax = ucl_0.90)) +
  geom_errorbar(width = 0, size = 10, alpha = 0.3) +
  geom_point(size = 3, alpha = 0.6) +
  labs(x = "Jaar", y = "Proportie bezette nestbuizen") +
  lims(y = c(0, NA)) +
  facet_grid(geb~type)
```
```{r, fig.height= 8, fig.width= 7}
bind_rows(
  results_index_diff_ref_geb %>%
    mutate(type = "nesten"),
  results_index_individu_diff_ref_geb %>%
    mutate(type = "individuen")
) %>% 
  ggplot(aes(x = jaar, y = mean_log, ymin = lcl_0.90_log, ymax = ucl_0.90_log, label = klasse, colour = klasse)) +
  geom_errorbar(width = 0, size = 10, alpha = 0.3) +
  geom_point(size = 7, alpha = 0.6) +
  geom_hline(yintercept = 0, linetype = 2) +
  geom_hline(yintercept = log(0.75), linetype = 3) +
  geom_hline(yintercept = log(1.33), linetype = 3) +
  geom_text(size = 4, colour = "black") +
  labs(y = "Verschil t.o.v. referentiejaar", x = "Jaar") +
  scale_y_continuous(breaks = breaks_log, labels = labels_show) +
  scale_color_manual(values = klasse_color) +
  theme(legend.position = "hide") +
  facet_grid(geb~type)
```
```{r, fig.height= 8, fig.width= 7}
bind_rows(
  results_index_diff_prevyear_geb %>%
    mutate(type = "nesten"),
  results_index_individu_diff_prevyear_geb %>%
    mutate(type = "individuen")
) %>% 
  mutate(periode = str_c(jaar_ref, "-", jaar)) %>%
  ggplot(aes(x = periode, y = mean_log, ymin = lcl_0.90_log, ymax = ucl_0.90_log, label = klasse, colour = klasse)) +
  geom_errorbar(width = 0, size = 10, alpha = 0.3) +
  geom_point(size = 7, alpha = 0.6) +
  geom_hline(yintercept = 0, linetype = 2) +
  geom_hline(yintercept = log(0.75), linetype = 3) +
  geom_hline(yintercept = log(1.33), linetype = 3) +
  geom_text(size = 4, colour = "black") +
  labs(y = "Verschil opeenvolgende jaren", x = "Periode") +
  scale_y_continuous(breaks = breaks_log, labels = labels_show) +
  scale_color_manual(values = klasse_color) +
  theme(legend.position = "hide") +
  facet_grid(geb~type)
```

## Model

### Aantallen

```{r}

analyseset_aantal_nesten_jaar <- analyseset_nesten_jaar %>%
  group_by(meetnet, locatie, gebied, jaar,, year_scaled, fjaar, soort_nl) %>%
  summarise(aantal = sum(aanwezig),
            n_nestkasten = n_distinct(sublocatie)) %>%
  ungroup() %>%
  mutate(soort_wet = "Muscardinus avellanarius")

analyseset_aantal_nesten_jaar %>%
  ggplot(aes(x = jaar, y = aantal, group = locatie)) +
  geom_point() +
  geom_line()

```


```{r}

calc_trend_nestkasten <- function(analyseset, select_seed = 5846){
  
  trendmodel_iid <- inla(formula = aantal ~ year_scaled +  
                                f(locatie, 
                                  model = "iid", 
                                  hyper = list(theta = list(prior = "pc.prec", param = c(1, 0.05)))),
                       family = "nbinomial",
                       data = analyseset,
                       offset = n_nestkasten,
                       control.compute = list(config = TRUE, waic = TRUE),
                       control.predictor = list(compute = TRUE))
  
  set.seed(select_seed)
  results_trend <- derive_trend(analyseset_species = analyseset, 
                              trendmodel_nbinom = trendmodel_iid)
  
  return(results_trend)
}

trend_nestkasten_1 <- calc_trend_nestkasten(analyseset_aantal_nesten_jaar)  

trendmodel_nestkasten <- inla(formula = aantal ~ year_scaled +  
                                f(locatie, 
                                  model = "iid", 
                                  hyper = list(theta = list(prior = "pc.prec", param = c(1, 0.05)))),
                       family = "nbinomial",
                       data = analyseset_aantal_nesten_jaar,
                       offset = n_nestkasten,
                       control.compute = list(config = TRUE, waic = TRUE),
                       control.predictor = list(compute = TRUE),
                       quantiles = c(0.025, 0.05, 0.5, 0.95, 0.975))


trend_aantal_nestkasten <- trendmodel_nestkasten$summary.fixed %>%
  rownames_to_column(var = "parameter")
```
### Proporties

```{r}
trendmodel_iid <- inla(formula = aanwezig ~ year_scaled +
                                f(sublocatie, 
                                  model = "iid", 
                                  hyper = list(theta = list(prior = "pc.prec", param = c(1, 0.05))))  + 
                                f(locatie,
                                  model = "iid", 
                                  hyper = list(theta = list(prior = "pc.prec", param = c(1, 0.05)))),
                       family = "binomial",
                       data = analyseset_nesten_jaar,
                       control.compute = list(config = TRUE, waic = TRUE),
                       control.predictor = list(compute = TRUE),
                       quantiles = c(0.025, 0.05, 0.5, 0.95, 0.975))

trend_nestkasten <- trendmodel_iid$summary.fixed %>%
  rownames_to_column(var = "parameter")

intercept <- (trend_nestkasten %>%
  filter(parameter == "(Intercept)"))$mean

trend <- (trend_nestkasten %>%
  filter(parameter == "year_scaled"))$mean

# prop jaar 1

prop_model <- tibble(year_scaled = 1:4,
                     trend_logit = trend,
                     intercept_logit = intercept) %>%
  mutate(prop_logit = intercept + year_scaled * trend_logit,
         prop = plogis(prop_logit)) 

derive_trend_prop <- function(sample) {
  
  s <- sample$latent %>%
    as.data.frame() %>%
    rownames_to_column(var = "parameter") %>%
    filter(str_detect(parameter, "year_scaled|Intercept")) %>%
    mutate(parameter = str_sub(parameter, end = -3)) %>%
    pivot_wider(names_from = parameter, values_from = V1) %>%
    mutate(prop_1 = plogis(`(Intercept)` + 1 * year_scaled),
           prop_5 = plogis(`(Intercept)` + 4 * year_scaled),
           trend_total_1_5 = (prop_5 / prop_1 - 1) * 100,
           trend_average_1_5 = ((trend_total_1_5/100 + 1) ^ (1/4) - 1) * 100) %>%
    pivot_longer(cols = c("(Intercept)", "year_scaled", "prop_1", "prop_5", "trend_total_1_5", "trend_average_1_5"), names_to = "parameter",
                 values_to = "value")
           
  return(s)
}

  samples <- inla.posterior.sample(1000, trendmodel_iid , seed = 5454 ,num.threads = "1:1")

  quantile_values <- c(0.025, 0.05, 0.20, 0.35,  0.65, 0.80, 0.95, 0.975)
  
  estimates_trend_prop <- map_df(samples, derive_trend_prop, .id = "sample") %>%
    group_by(parameter) %>%
    mutate(mean = mean(value),
           sd = sd(value)) %>%
    ungroup() %>%
    group_by(parameter, mean, sd) %>%
    summarise(qs = quantile(value, quantile_values, na.rm =TRUE), prob = quantile_values) %>%
    ungroup() %>%
    mutate(l_u = ifelse(prob < 0.5, "lcl", "ucl"),
           ci = ifelse(prob %in% c(0.025, 0.975), "0.95",
                       ifelse(prob %in% c(0.05, 0.95), "0.90",
                              ifelse(prob %in% c(0.20, 0.80), "0.60",
                                     ifelse(prob %in% c(0.35, 0.65), "0.30", NA)))),
           type = str_c(l_u, "_", ci)) %>%
    select(-prob, -l_u, -ci) %>%
    spread(key = type, value = qs) 
  
  overzicht_trend_tabel_nestbuizen <- estimates_trend_prop %>%
    filter(parameter %in% c("trend_total_1_5", "trend_average_1_5")) %>%
    mutate( n_jaar = 5,
         treshold_low = ifelse(parameter == "trend_average_1_5", 
                               round((exp(log(0.75)/(n_jaar - 1)) - 1) * 100, 1),
                               -25),
         treshold_high = ifelse(parameter == "trend_average_1_5", 
                                round((exp(log(1.33)/(n_jaar - 1)) - 1) * 100, 1),
                                33)) %>%
  ungroup() %>%
  mutate(klasse = classification_tw(lcl_0.95, ucl_0.95, threshold_low = treshold_low, treshold_high =  treshold_high, reference = 0)) %>%
    mutate(trend = round(mean, 1),
         trend_lcl = round(lcl_0.95, 1),
         trend_ucl = round(ucl_0.95, 1),
         trend_tbl = str_c(ifelse(trend > 0, "+", ""),
                           trend, "% (",
                           ifelse(trend_lcl > 0, "+", ""),
                           trend_lcl, "%; ",
                           ifelse(trend_ucl > 0, "+", ""),
                           trend_ucl, "%)")
         ) %>%
  mutate(periode = "2020 - 2024",
         soort_nl = "Hazelmuis") %>%
  select(parameter, soort_nl, periode, klasse, trend_tbl) %>%
  spread(key = "parameter", value = "trend_tbl") %>%
  mutate(klasse = as.character(klasse)) %>%
  select("Nederlandse naam" = soort_nl,  Periode = periode, Klasse = klasse,  "Jaarlijkse wijziging" = trend_average_1_5, "Wijziging over de looptijd" = trend_total_1_5) %>%
    mutate(meetnet = "Hazelmuis - nestbuizen")

```

```{r}
overzicht_trend <- overzicht_trend_tabel_nestbuizen %>%
  bind_rows(overzicht_trend_tabel_transect %>%
              mutate(meetnet = "Hazelmuis - transecten")) %>%
  select(Meetnet = meetnet, Periode,"Jaarlijkse wijziging", "Wijziging over de looptijd", Klasse)

overzicht_trend %>%
  write.csv2("../output/trend_hazelmuis_0_95.csv")
```

