# Libellen - Populatietelling per locatie"

```{r}

species_group <- "libellen"
protocol_selection <- "Libellen - Populatietelling per locatie"
name_analysis <- "libellen_gebiedstelling"

set.seed(47830)
```

## Selectie analyseset

```{r select data gebieds, warning = FALSE}

protocol_selection <- "Libellen - Populatietelling per locatie"

locatie_detail <- get_locations_smp() %>%
  st_drop_geometry() %>%
  filter(locatie_type == "locatie") %>%
  select(meetnet, locatie, is_active, is_sample)

visits <- get_visits_smp("libellen")
counts <- get_counts_smp(species_group = "libellen", count_aggregation = "individuals") %>%
  filter(primaire_soort)

count_period <- get_characteristics_smp(species_group = "libellen") %>%
  mutate(doy_min = as.numeric(format(start_telperiode, "%j")),
         doy_max = as.numeric(format(einde_telperiode, "%j")),
         doy_mid = doy_min + round((doy_max - doy_min)/2, 0)) %>%
  distinct(meetnet, protocol, doy_min, doy_max, doy_mid)

meetnetten_selection <- visits %>%
  filter(protocol == protocol_selection) %>%
  group_by(meetnet, protocol) %>%
  summarise(n_jaar = n_distinct(jaar)) %>%
  filter(n_jaar >= 3)

visits_selection <- visits %>%
  filter(meetnet %in% meetnetten_selection$meetnet) %>%
  filter(validatie != -1) %>%
  left_join(locatie_detail, by = c("meetnet", "locatie")) %>%
  filter(voor_analyse & !is.na(is_active)) %>%
  left_join(count_period, by = c("meetnet", "protocol")) %>%
  mutate(doy_scaled = (doy - doy_mid)/28,
         fjaar = factor(jaar)) %>%
  group_by(soortgroep, meetnet, protocol, locatie, jaar, fjaar) %>%
  mutate(n_obs = n_distinct(visit_id)) %>%
  ungroup()

counts_selection <- visits_selection %>%
  select(soortgroep, meetnet, protocol, locatie, jaar, datum, doy, doy_scaled, doy_min, doy_max, doy_mid, visit_id, n_obs, voor_analyse, is_active, is_sample, bezoek_status) %>%
  left_join(select(counts, visit_id, soort_nl, soort_wet, aantal), by = "visit_id")

```





```{r}

counts_analysis <- counts_selection %>%
  filter(meetnet != "Hoogveenglanslibel") %>%
  group_by(meetnet, locatie) %>%
  mutate(n_jaren = n_distinct(jaar),
            max_count = max(aantal)) %>%
  ungroup() %>%
  filter(n_jaren > 1 & max_count > 0) %>%
  mutate(fjaar = factor(jaar),
         locatie = factor(locatie),
         doy_scaled_2 = doy_scaled * doy_scaled)
  
analyseset_by_species <- counts_analysis %>%
  group_by(meetnet) %>%
  nest()


``` 

```{r}

write_vc(counts_analysis, 
         file = str_c("analyseset_", name_analysis), 
         root = "../output/temp", 
         sorting = c("meetnet", "locatie", "visit_id"), 
         strict = FALSE)
  
```
## Verkenning

```{r}
analysest_speerwaterjuffer <- counts_analysis %>%
  filter(soort_nl == "Speerwaterjuffer") %>% 
  mutate(locatie = as.character(locatie),
           locatie = as.factor(locatie),
           jaar_centered = jaar - min(jaar),
           doy_centered = doy - min(doy))

overzicht_speer <- analysest_speerwaterjuffer %>%
  group_by(soort_wet, jaar, locatie) %>%
  summarise(n_visits = n_distinct(visit_id),
            mean_aantal = sum(aantal)/n_visits) %>%
  ungroup() 

overzicht_speer %>%
  ggplot(aes(x = jaar, y = mean_aantal, group = locatie, colour = locatie, shape = factor(n_visits))) +
  geom_point(alpha = 0.6, size = 3) +
  geom_line(size = 0.5, alpha = 0.8, linetype = 2) +
  facet_wrap(~soort_wet) +
  labs(shape = "Number of visits", x = "Year", y = "Average count per visit", colour = "Location") +
  theme(strip.text = element_text(face = "italic"))

ggsave("../output/speerwaterjuffer_locaties.png", height = 5)
```


## Modelering

```{r}

formula_indexmodel <- as.formula("aantal ~ f(jaar_centered, model = \"rw1\", 
                                  hyper = list(theta = list(prior = \"pc.prec\", param = c(0.3, 0.05)))) + 
                                f(doy_centered, model = \"rw2\", 
                                  hyper = list(theta = list(prior = \"pc.prec\", param = c(0.01, 0.05)))) + 
                                 f(locatie, model = \"iid\", 
                                   hyper = list(theta = list(prior = \"pc.prec\", param = c(1, 0.05))))")
  
inlamodel_index <- inla(formula_indexmodel,
              family = "nbinomial",
              data = analysest_speerwaterjuffer,
              control.compute = list(config = TRUE, waic = TRUE),
              control.predictor = list(compute = TRUE))

result_index <- derive_index_rw_inla(analysest_speerwaterjuffer, inlamodel_rw = inlamodel_index)
  
inlamodel_trend <- fit_trendmodel_rw_nbinom_inla(analysest_speerwaterjuffer)
  
result_trend <- derive_trend(analyseset_species = analysest_speerwaterjuffer, trendmodel_nbinom = inlamodel_trend)

# vanaf 2020 2 extra locaties

analysest_speerwaterjuffer_2020 <- counts_analysis %>%
  filter(soort_nl == "Speerwaterjuffer",
         jaar >= 2020) %>% 
  mutate(locatie = as.character(locatie),
           locatie = as.factor(locatie),
           jaar_centered = jaar - min(jaar),
           doy_centered = doy - min(doy))

inlamodel_index_2020 <- inla(formula_indexmodel,
              family = "nbinomial",
              data = analysest_speerwaterjuffer_2020,
              control.compute = list(config = TRUE, waic = TRUE),
              control.predictor = list(compute = TRUE))

result_index_2020 <- derive_index_rw_inla(analysest_speerwaterjuffer_2020, inlamodel_rw = inlamodel_index_2020)
  
inlamodel_trend_2020 <- fit_trendmodel_rw_nbinom_inla(analysest_speerwaterjuffer_2020)
  
result_trend_2020 <- derive_trend(analyseset_species = analysest_speerwaterjuffer_2020, trendmodel_nbinom = inlamodel_trend_2020)

```




```{r}

seed <- 20211124

set.seed(seed)

models_inla <- analyseset_by_species %>%
  mutate(use_seed = TRUE) %>%
  mutate(indexmodel = map(data, fit_indexmodel_rw_nbinom_inla),
         trendmodel = map(data, fit_trendmodel_rw_nbinom_inla))

results_indexmodel_gebied <- models_inla %>%
  transmute(index = pmap(list(data, indexmodel, use_seed), derive_index_rw_inla)) %>%
  unnest(cols = c(meetnet, index))

results_trendmodel_gebied  <- models_inla %>%
  transmute(trend = map2(data, trendmodel, derive_trend)) %>%
  select(meetnet, trend) %>%
  unnest()

waic_index_gebied  <- models_inla %>%
  transmute(waic_index =  map2(data, indexmodel, get_waic)) %>%
  select(meetnet, waic_index) %>%
  unnest() %>%
  mutate(model = "indexmodel")

waic_trend_gebied  <- models_inla %>%
  transmute(waic_trend =  map2(data, trendmodel, get_waic)) %>%
  select(meetnet, waic_trend) %>%
  unnest() %>%
  mutate(model = "trendmodel")

results_waic_gebied <- bind_rows(waic_index_gebied, 
                         waic_trend_gebied) %>%
  spread(key = "model", value = "waic") %>%
  mutate(diff_waic = trendmodel - indexmodel,
         type_trend = ifelse(diff_waic > 0,
                               "Niet lineair",
                               ifelse(diff_waic > -2,
                                      "Quasi lineair", "Lineair")))
```




```{r}
results_index <- results_indexmodel %>%
  select(meetnet, index) %>%
  unnest(index)

results_max_count <- results_indexmodel %>%
  select(meetnet, max_count) %>%
  unnest(max_count)

# results_diff_years <- results_indexmodel %>%
#   select(meetnet, diff_years) %>%
#   unnest(diff_years)

results_trend <- results_trendmodel %>%
  select(meetnet, trend) %>%
  unnest(trend)

results_waic_index <- results_trendmodel %>%
  select(meetnet, waic_index) %>%
  unnest(waic_index) %>%
  mutate(model = "indexmodel")

results_waic_trend <- results_trendmodel %>%
  select(meetnet, waic_trend) %>%
  unnest(waic_trend) %>%
  mutate(model = "trendmodel")

results_waic <- bind_rows(results_waic_index, 
                         results_waic_trend) %>%
  spread(key = "model", value = "waic") %>%
  mutate(diff_waic = trendmodel - indexmodel,
         type_trend = ifelse(diff_waic > 0,
                               "Niet lineair",
                               ifelse(diff_waic > -2,
                                      "Quasi lineair", "Lineair")))

```

```{r}

bind_rows(results_index, 
          results_max_count) %>%
  write_vc(file = "results_indexmodel", 
         root = here(str_c("analysis_", species_group, "/output/temp")), 
         sorting = c("parameter", "soort_nl", "jaar"),
         strict = FALSE)

results_trend %>%
  write_vc(file = "results_trendmodel", 
         root = here(str_c("analysis_", species_group, "/output/temp")), 
         sorting = c("parameter", "soort_nl"), strict = FALSE)

results_waic %>%
  write_vc(file = "results_waic", 
         root = here(str_c("analysis_", species_group, "/output/temp")), 
         sorting = c("parameter", "soort_nl"),
         strict = FALSE)

```


## Validatie

```{r}
model_validation <- models_inla %>%
  transmute(dispersion_check_model = map(indexmodel, dispersion_check),
            distribution_check_model = map(indexmodel, fast_distribution_check),
            iid_check = map(indexmodel, check_random_effect)
            )


dispersion <- model_validation %>%
  transmute(dispersion_data = map(dispersion_check_model, "data"),
            dispersion_model = map(dispersion_check_model, "model")) %>%
  select(meetnet, dispersion_data, dispersion_model) %>%
  unnest(c(dispersion_data, dispersion_model))

distribution <- model_validation %>%
  select(meetnet, distribution_check_model) %>%
  unnest(distribution_check_model) %>%
  filter(lcl < 0.98 & ucl < 1)

iid_checked <- model_validation %>%
  select(meetnet, iid_check) %>%
  unnest(iid_check)

```

### Dispersie

```{r}

ggplot(data = dispersion, aes(x = dispersion_model)) +
      geom_density() +
      geom_vline(data = dispersion, aes(xintercept = dispersion_data), linetype = 2) +
      facet_wrap(~meetnet, scales = "free_x")
     
```

### Distributie

```{r, fig.height= 8}
distribution %>%
  mutate(
      median = .data$ecdf / .data$median,
      lcl = .data$ecdf / .data$lcl,
      ucl = .data$ecdf / .data$ucl
    ) %>%
  ggplot(aes_string(x = "x", y = "median")) +
   # geom_blank(data = data.frame(x = min(x$x), median = c(0.95, 1.05))) +
    geom_hline(yintercept = 1, linetype = 2) +
    geom_line(aes_string(y = "lcl"), linetype = 3, alpha = 0.5) +
    geom_line(aes_string(y = "ucl"), linetype = 3, alpha = 0.5) +
    geom_ribbon(alpha = 0.1, aes_string(ymin = "lcl", ymax = "ucl")) +
    geom_line() +
    scale_y_continuous("observed / expected", labels = scales::percent) +
    facet_wrap(~meetnet, scales = "free", ncol = 2)
```

### Random effect

```{r}

iid_checked_plot <- iid_checked %>%
  group_by(meetnet) %>%
  mutate(x_c = sim_iid - mean(sim_iid),
         y = exp(x_c + log(1))) %>%
  ungroup()

iid_checked_plot %>%
  mutate(sigma_tekst = str_c("sigma = ", round(sigma, 3))) %>%
  ggplot(aes(x = y)) +
      geom_density() +
      scale_x_continuous("relative effect", labels = scales::percent) +
      facet_wrap(~meetnet + sigma_tekst, scales = "free")
    
```

```{r}
iid_checked_plot %>%
  filter(meetnet == "Speerwaterjuffer") %>%
  mutate(sigma_tekst = str_c("sigma = ", round(sigma, 3))) %>%
  ggplot(aes(x = y)) +
      geom_density() +
      scale_x_continuous("relative effect", labels = scales::percent) +
      facet_wrap(~meetnet + sigma_tekst, scales = "free")
```



## Visualisatie model

```{r}
model_simulate <- models_inlabru %>%
  transmute(data_simulated = map2(data, indexmodel, simulate_data_model_inlabru))

results_data_simulated <- model_simulate %>%
  unnest(data_simulated)
```




```{r, warning=FALSE, fig.height= 9}

ggplot(data = results_data_simulated, aes(x = doy)) + 
  geom_line(aes(y = mean, group = loc_id, colour = factor(loc_id)), linetype = 2 ) +
  geom_point(aes(y = y_obs), alpha = 0.5, size = 1) +
  geom_line(aes(y = mean_year), size = 1, colour = "black") +
  geom_ribbon(aes(ymin = lci_0.95_year, ymax = uci_0.95_year), alpha = 0.3) +
  facet_grid(soort_nl ~ jaar, scales = "free") +
  theme(legend.position = "none")
```

### Maanwaterjuffer

```{r, fig.height= 9}


ggplot(data = filter(results_data_simulated, meetnet == "Maanwaterjuffer"), aes(x = doy)) + 
  geom_line(aes(y = mean, group = loc_id, colour = factor(loc_id)), linetype = 2 ) +
  geom_point(aes(y = y_obs), alpha = 0.5, size = 1) +
  geom_line(aes(y = mean_year), size = 1, colour = "black") +
  geom_ribbon(aes(ymin = lci_0.95_year, ymax = uci_0.95_year), alpha = 0.3) +
  facet_wrap( ~ jaar) +
  theme(legend.position = "none")
```

### Speerwaterjuffer

```{r, fig.height= 9}

ggplot(data = filter(results_data_simulated, meetnet == "Speerwaterjuffer"), aes(x = doy)) + 
  geom_line(aes(y = mean, group = loc_id, colour = factor(loc_id)), linetype = 2, alpha = 0.2) +
  geom_point(aes(y = y_obs), alpha = 0.5, size = 1) +
  geom_line(aes(y = mean_year), size = 1, colour = "black") +
  geom_ribbon(aes(ymin = lci_0.95_year, ymax = uci_0.95_year), alpha = 0.3) +
  facet_wrap( ~ jaar) +
  theme(legend.position = "none")
```
```{r, fig.width= 9, fig.height= 9}
# analyseset_species <- counts_analysis %>%
#   filter(meetnet == "Speerwaterjuffer")
# 
# analyseset_species %>%
#   ggplot(aes(x = jaar, y = aantal)) +
#   geom_point() +
#   facet_wrap(~locatie)

counts_analysis %>%
  ggplot(aes(x = locatie, y =aantal)) +
  geom_point(alpha = 0.4, size = 2) +
  coord_flip() +
  facet_wrap(~meetnet, scales = "free_y", ncol = 1)
  

```


### Vergelijking tussen de jaren


```{r}

verschil_jaren_ref <- result_index_2020 %>%
  filter(parameter == "index") %>%
  filter(!is.na(mean)) %>%
  mutate(klasse = classification(lcl_0.90, ucl_0.90, threshold = c(0.75, 1.33), reference = 1),
         klasse = format(klasse, type = "markdown"))
  
verschil_jaren_ref_add <- verschil_jaren_ref %>%
  distinct(soort_nl, soort_wet, ref_jaar) %>%
  mutate(jaar = ref_jaar,
        mean = 1,
         klasse = "R") 

verschil_jaren_ref <- verschil_jaren_ref %>%
  bind_rows(verschil_jaren_ref_add) %>%
  mutate(mean_log = log(mean) + 1,
          lcl_0.90_log = log(lcl_0.90) + 1,
         ucl_0.90_log = log(ucl_0.90) + 1)

c(rev(traffic_palette(7)), "grey65", "grey35", "grey50") %>%
  setNames(
    c("++", "+", "+~", "~", "-~", "-", "--", "?+", "?-", "?")
  ) -> klasse_color
klasse_color[4] <- inbo_steun_blauw

breaks_log <- log(c(0.01, 0.1, 0.25, 0.5, 0.75, 1, 1.33, 2, 3, 6)) + 1
labels_show <- str_c(c(-99, -90, -75, -50, -25, 0, 33, 100, 200, 500), " %")

verschil_jaren_ref %>%
  mutate(klasse = str_remove_all(klasse, "`")) %>%
  ggplot(aes(x = jaar, y = mean_log, ymin = lcl_0.90_log, ymax = ucl_0.90_log, label = klasse, colour = klasse)) +
  geom_errorbar(width = 0, size = 10, alpha = 0.3) +
  geom_point(size = 7, alpha = 0.6) +
  geom_hline(yintercept = 1, linetype = 2) +
  geom_hline(yintercept = log(0.75) + 1, linetype = 3) +
  geom_hline(yintercept = log(1.33) + 1, linetype = 3) +
  geom_text(size = 4, colour = "black") +
  labs(y = "Difference compared to reference year", x = "Year") +
  scale_y_continuous(breaks = breaks_log, labels = labels_show) +
  scale_color_manual(values = klasse_color) +
  theme(legend.position = "hide",strip.text = element_text(face = "italic")) +
  facet_wrap(~soort_wet, scales = "free_y")

ggsave("../output/speerwaterjuffer_index_ref2020.png", width = 5, height = 5)
```


```{r}

verschil_jaren_ref <- result_index %>%
  filter(parameter == "index") %>%
  filter(!is.na(mean)) %>%
  mutate(klasse = classification(lcl_0.90, ucl_0.90, threshold = c(0.75, 1.33), reference = 1),
         klasse = format(klasse, type = "markdown"))
  
verschil_jaren_ref_add <- verschil_jaren_ref %>%
  distinct(soort_nl, soort_wet, ref_jaar) %>%
  mutate(jaar = ref_jaar,
        mean = 1,
         klasse = "R") 

verschil_jaren_ref <- verschil_jaren_ref %>%
  bind_rows(verschil_jaren_ref_add) %>%
  mutate(mean_log = log(mean) + 1,
          lcl_0.90_log = log(lcl_0.90) + 1,
         ucl_0.90_log = log(ucl_0.90) + 1)

c(rev(traffic_palette(7)), "grey65", "grey35", "grey50") %>%
  setNames(
    c("++", "+", "+~", "~", "-~", "-", "--", "?+", "?-", "?")
  ) -> klasse_color
klasse_color[4] <- inbo_steun_blauw

breaks_log <- log(c(0.01, 0.1, 0.25, 0.5, 0.75, 1, 1.33, 2, 3, 6)) + 1
labels_show <- str_c(c(-99, -90, -75, -50, -25, 0, 33, 100, 200, 500), " %")

verschil_jaren_ref %>%
  mutate(klasse = str_remove_all(klasse, "`")) %>%
  ggplot(aes(x = jaar, y = mean_log, ymin = lcl_0.90_log, ymax = ucl_0.90_log, label = klasse, colour = klasse)) +
  geom_errorbar(width = 0, size = 10, alpha = 0.3) +
  geom_point(size = 7, alpha = 0.6) +
  geom_hline(yintercept = 1, linetype = 2) +
  geom_hline(yintercept = log(0.75) + 1, linetype = 3) +
  geom_hline(yintercept = log(1.33) + 1, linetype = 3) +
  geom_text(size = 4, colour = "black") +
  labs(y = "Difference compared to reference year", x = "Year") +
  scale_y_continuous(breaks = breaks_log, labels = labels_show) +
  scale_color_manual(values = klasse_color) +
  theme(legend.position = "hide",strip.text = element_text(face = "italic")) +
  facet_wrap(~soort_wet, scales = "free_y")

ggsave("../output/speerwaterjuffer_index_ref2017.png", width = 7, height = 5)
```


```{r}
verschil_vorigjaar <- result_index %>%
  filter(parameter == "diff_previous_year") %>%
  mutate(periode = str_c(lag(jaar), " - ", jaar )) %>%
  filter(!is.na(mean)) %>%
  mutate(klasse = classification(lcl_0.90, ucl_0.90, threshold = c(0.75, 1.33), reference = 1),
         klasse = format(klasse, type = "markdown")) %>%
  mutate(mean_log = log(mean) + 1,
          lcl_0.90_log = log(lcl_0.90) + 1,
         ucl_0.90_log = log(ucl_0.90) + 1)
  
```

```{r}
verschil_vorigjaar %>%
  select( soort_nl, soort_wet, periode, klasse) %>%
  spread(key = "periode", value = "klasse") %>%
  ungroup() %>%
  select(-soort_wet) %>%
  rename("Nederlandse naam" = soort_nl) %>%
  kbl(caption = "Verschil in aantallen voor opeenvolgende jaren",
      booktabs = TRUE,
      escape = FALSE,
      align = "lcccccc") %>%
kable_styling()
```

```{r}
verschil_vorigjaar %>%
  mutate(klasse = str_remove_all(klasse, "`")) %>%
  ggplot(aes(x = periode, y = mean_log, ymin = lcl_0.90_log, ymax = ucl_0.90_log, label = klasse, colour = klasse)) +
  geom_errorbar(width = 0, size = 10, alpha = 0.3) +
  geom_point(size = 7, alpha = 0.6) +
  geom_hline(yintercept = 1, linetype = 2) +
  geom_hline(yintercept = log(0.75) + 1, linetype = 3) +
  geom_hline(yintercept = log(1.33) + 1, linetype = 3) +
  geom_text(size = 4, colour = "black") +
  labs(y = "Verschil opeenvolgende jarenr", x = "Jaar") +
  scale_y_continuous(breaks = breaks_log, labels = labels_show) +
  scale_color_manual(values = klasse_color) +
  theme(legend.position = "hide",
        axis.text.x = element_text(angle = 45)) +
  facet_wrap(~soort_nl, scales = "free_y")
```

## Documenteer analyse

```{r}

mypath <- here(str_c("analysis_", species_group, "/output/temp"))

hashes <-
    tibble(filepath = str_c(mypath, "/",
        list.files(path = mypath,
            recursive = TRUE)
      )) %>%
    mutate(name_analysis = name_analysis,
           version = Sys.Date(),
           filename = str_match(filepath, "(.+\\/)*(.+)")[,3],
           md5 = map(filepath, function(x) {
                           file(x) %>% md5 %>% str_c(collapse = '')
                         }) %>% as.character,
           sha256 = map(filepath, function(x) {
                          file(x) %>% sha256 %>% str_c(collapse = '')
                          }) %>% as.character
           ) %>%
    select(name_analysis,
           version,
           filename,
           md5,
           sha256)

file_name <- here(str_c("analysis_", species_group, "/output/analysis_hashes.csv"))

if (!file.exists(file_name)) {
  
  new_analysis <- TRUE
  
  analysis_hashes <- hashes

} else {
  
  analysis_hashes <- read_csv(file_name)
  
  hashes_new <- hashes %>%
    anti_join(analysis_hashes, by = c("name_analysis", "filename", "md5", "sha256"))
  
  new_analysis <- nrow(hashes_new) > 0
  
  analysis_hashes <- bind_rows(analysis_hashes,
                               hashes)
  
}

if (new_analysis) {
  
  new_path <- here(str_c("analysis_", species_group, "/output/", name_analysis, "_", Sys.Date()))
  
  if (!dir.exists(new_path)) {
    
    dir.create(new_path)
    file.copy(from = str_c(mypath, "/analyseset.tsv"), to = str_c(new_path, "/analyseset.tsv"), overwrite = TRUE)
    file.copy(from = str_c(mypath, "/analyseset.yml"), to = str_c(new_path, "/analyseset.yml"), overwrite = TRUE)
    file.copy(from = str_c(mypath, "/results_indexmodel.tsv"), to = str_c(new_path, "/results_indexmodel.tsv"), overwrite = TRUE)
    file.copy(from = str_c(mypath, "/results_indexmodel.yml"), to = str_c(new_path, "/results_indexmodel.yml"), overwrite = TRUE)
    file.copy(from = str_c(mypath, "/results_trendmodel.tsv"), to = str_c(new_path, "/results_trendmodel.tsv"), overwrite = TRUE)
    file.copy(from = str_c(mypath, "/results_trendmodel.yml"), to = str_c(new_path, "/results_trendmodel.yml"), overwrite = TRUE)
    file.copy(from = str_c(mypath, "/results_waic.tsv"), to = str_c(new_path, "/results_waic.tsv"), overwrite = TRUE)
    file.copy(from = str_c(mypath, "/results_waic.yml"), to = str_c(new_path, "/results_waic.yml"), overwrite = TRUE)
  }
  
  analysis_hashes %>%
    write_csv(file_name)
  
}

```



### Effect van lengte tijdsreeks op index

#### Gevlekte witsnuitlibel

```{r}

soort <- "Gevlekte witsnuitlibel"

analyseset_soort <- counts_analysis %>%
  filter(meetnet == soort)

model_soort <- analyseset_soort %>%
  fit_indexmodel_nbinom_inlabru() 
  
index_soort_2020 <- derive_index_inlabru(analyseset_soort, model_soort) %>%
  mutate(tijdsreeks = "2016-2020")

analyseset_soort <- counts_analysis %>%
  filter(meetnet == soort) %>%
  filter(jaar <= 2019)

model_soort <- analyseset_soort %>%
  fit_indexmodel_nbinom_inlabru() 
  
index_soort_2019 <- derive_index_inlabru(analyseset_soort, model_soort) %>%
  mutate(tijdsreeks = "2016-2019")

analyseset_soort <- counts_analysis %>%
  filter(meetnet == soort) %>%
  filter(jaar <= 2018)

model_soort <- analyseset_soort %>%
  fit_indexmodel_nbinom_inlabru() 
  
index_soort_2018 <- derive_index_inlabru(analyseset_soort, model_soort) %>%
  mutate(tijdsreeks = "2016-2018")

index_soort <- bind_rows(
  index_soort_2018,
  index_soort_2019,
  index_soort_2020
  
)

```



```{r}

index_soort %>%
  mutate(ref_jaar_tekst = str_c("ref. jaar = ", ref_jaar)) %>%
  filter(parameter == "index") %>%
  ggplot(aes(y = mean, ymin = lcl_0.95, ymax = ucl_0.95, x = as.character(jaar), group = soort_nl)) +
  geom_point() +
  geom_errorbar(width = 0.1) +
  geom_hline(yintercept = 1, linetype = 3) +
  geom_line( colour = inbo.steun.blauw, linetype = 2) +
  #geom_ribbon(alpha = 0.2) + 
  labs(y = "Jaarlijkse index", x = "Jaar") +
  #scale_x_continuous(breaks= c(2017, 2018)) +
  scale_y_continuous(labels = scales::percent, limits = c(0,NA)) +
  facet_wrap(~ tijdsreeks + ref_jaar_tekst)
```

#### Maanwaterjuffer

```{r}

soort <- "Maanwaterjuffer"

analyseset_soort <- counts_analysis %>%
  filter(meetnet == soort)

model_soort <- analyseset_soort %>%
  fit_indexmodel_nbinom_inlabru() 
  
index_soort_2020 <- derive_index_inlabru(analyseset_soort, model_soort) %>%
  mutate(tijdsreeks = "2016-2020")

analyseset_soort <- counts_analysis %>%
  filter(meetnet == soort) %>%
  filter(jaar <= 2019)

model_soort <- analyseset_soort %>%
  fit_indexmodel_nbinom_inlabru() 
  
index_soort_2019 <- derive_index_inlabru(analyseset_soort, model_soort) %>%
  mutate(tijdsreeks = "2016-2019")

analyseset_soort <- counts_analysis %>%
  filter(meetnet == soort) %>%
  filter(jaar <= 2018)

model_soort <- analyseset_soort %>%
  fit_indexmodel_nbinom_inlabru() 
  
index_soort_2018 <- derive_index_inlabru(analyseset_soort, model_soort) %>%
  mutate(tijdsreeks = "2016-2018")

index_soort <- bind_rows(
  index_soort_2018,
  index_soort_2019,
  index_soort_2020
  
)

```



```{r}

index_soort %>%
  mutate(ref_jaar_tekst = str_c("ref. jaar = ", ref_jaar)) %>%
  filter(parameter == "index") %>%
  ggplot(aes(y = mean, ymin = lcl_0.95, ymax = ucl_0.95, x = as.character(jaar), group = soort_nl)) +
  geom_point() +
  geom_errorbar(width = 0.1) +
  geom_hline(yintercept = 1, linetype = 3) +
  geom_line( colour = inbo.steun.blauw, linetype = 2) +
  #geom_ribbon(alpha = 0.2) + 
  labs(y = "Jaarlijkse index", x = "Jaar") +
  #scale_x_continuous(breaks= c(2017, 2018)) +
  scale_y_continuous(labels = scales::percent, limits = c(0,NA)) +
  facet_wrap(~ tijdsreeks + ref_jaar_tekst)
```

