# Inleiding

```{r}

libellen_taxonomy <- get_taxonomy_smp() %>%
  select(genus, meetnet = soort_nl, soort_wet, species_order)

meetnet_characteristics <- get_characteristics_smp(species_group = "libellen") %>%
  left_join(libellen_taxonomy, by = "meetnet")  %>%
  filter(is_sample) %>%
  arrange(species_order) %>%
  mutate(protocol = ifelse(meetnet %in% c("Beekrombout", "Rivierrombout"), "Transecttelling Larvendhuidjes",
                           ifelse(protocol == "Libellen - Transect", "Transecttelling imago's",
                                  ifelse(protocol == "Libellen - Populatietelling per locatie", "Gebiedstelling imago's", NA))))

meetnet_characteristics_results <- meetnet_characteristics %>%
  filter(! meetnet %in% c("Sierlijke witsnuitlibel", "Beekrombout", "Hoogveenglanslibel"))

meetnetten_links <- str_c(str_c("[", meetnet_characteristics_results$meetnet, "]", collapse = ", "))

```


Betrouwbare informatie over de toestand en trends van dier- en plantensoorten in Vlaanderen is van
groot belang voor de onderbouwing van het Vlaamse soortenbeleid en voor de rapportage over de Natura 2000-soorten aan Europa [@adriaens_monitoring_2011]. Daarom werden in de periode 2016-2018 soortenmeetnetten opgestart voor de langetermijn monitoring van 65 Vlaamse en Europees prioritaire soorten [@westra_voortgangsrapport_2019]. Elk meetnet bestaat uit een aantal vooraf vastgelegde locaties, waar een of meerdere soorten via een gestandaardiseerd methode geteld worden [@de_knijf_monitoring_2014]. 

De soortenmeetnetten zijn een citizen science project: vrijwilligers voeren de tellingen uit. Natuurpunt Studie staat in voor de coördinatie en aansturing van de vrijwilligers en het Instituut voor Natuur- en Bosonderzoek (INBO) verwerkt de telgegevens. Het Agentschap voor Natuur en Bos (ANB) en het INBO staan in voor de financiering. Voor de uitvoering van de libellenmeetnetten konden we bovendien rekenen op de steun van de Libellenvereniging Vlaanderen vzw. Voor de planning van de tellingen en het invoeren van gegevens werd het webportaal [meetnetten.be](https://www.meetnetten.be) ontwikkeld. 

In dit rapport stellen we de eerste resultaten voor van de verschillende libellenmeetnetten [@de_knijf_monitoringsprotocol_2019]. We geven eerst wat achtergrond over het [ontwerp van de libellenmeetnetten] en de [analyse van de telgegevens]. Daarna maken we een [verkenning van de getelde aantallen] en geven we een [overzicht van de resultaten] van de statistische analyses. Ten slotte bespreken we de resultaten voor elk meetnet (`r meetnetten_links`).     

`r ifelse(doc.type != "html", "Dit rapport bevat enkele interactieve figuren die alleen kunnen bekeken worden op de [website versie](https://inbo.github.io/soortenmeetnetten-libellenrapport-2021/) van dit rapport.", "")`

