# Methode

## Kenmerken van de libellenmeetnetten

```{r}

meetnet_characteristics <- get_characteristics_smp(species_group = "libellen")

meetnet_characteristics %>%
  filter(is_sample) %>%
  select(meetnet, protocol, type, "aantal locaties" = n_locaties , 'duur meetcyclus'= duur_meetcyclus, startjaar = opstartjaar) %>%
  unique() %>%
  arrange(protocol, meetnet) %>%
  kable(caption = "Overzicht van de karakteristieken van de libellenmeetnetten: veldprotocol, type meetnet (integraal of steekproef), aantal meetnetlocaties, meetcyclus in jaren en het jaar waarin het meetnet werd opgestart", 
        row.names = FALSE, 
        booktabs = TRUE,
        format = "html") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  column_spec(5, width = "2cm")
  
```

```{r}
meetnet_characteristics %>%
  filter(soortgroep == "libellen") %>%
  arrange(protocol, meetnet) %>%
  mutate(start_telperiode = format(start_telperiode, "%d/%m"),
         einde_telperiode = format(einde_telperiode, "%d/%m")) %>%
  select(meetnet,  'Bezoeken (/jaar)' = bezoeken, 'Begin telperiode' = start_telperiode, 'Einde telperiode' = einde_telperiode) %>%
  unique() %>%
  kable(caption = "Overzicht van de karakteristieken van de libellenmeetnetten: aantal bezoeken per jaar, begin en einde van de telperiode", row.names = FALSE, booktabs = TRUE, align = c("l", "c", "c", "c")) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  collapse_rows(columns = 1)
```

## Overzicht meetnetlocaties

```{r}

locaties <- get_locations_smp(species_group = "libellen") %>%
  add_tag_utm5() %>%
  st_drop_geometry()

locaties_utm5 <- read_utm5() %>%
  inner_join(locaties, by = "tag_utm5") %>%
  group_by(tag_utm5, meetnet) %>%
  mutate(label = str_c(unique(meetnet), " (", dplyr::n(), ")")) %>%
  ungroup() %>%
  group_by(tag_utm5) %>%
  mutate(label = str_c(unique(label), collapse = ", "),
         n = dplyr::n()) %>%
  ungroup() %>%
  st_transform(crs = 31370) %>%
  st_centroid() 

locaties_utm5_jitter <- rbind(
  locaties_utm5 %>%
  filter(n > 1) %>%
  st_jitter(2000),
  locaties_utm5 %>%
  filter(n == 1)) %>%
  st_transform(crs = 4326)
  
locaties_utm5 <- locaties_utm5 %>%
  st_transform(crs =4326)

utm5 <- read_utm5() %>%
  st_transform(crs =4326)
```

```{r}

locaties_shared <- SharedData$new(locaties_utm5)

bscols(
  list(
    bscols(
      widths = c(8, 4),
      NULL,
      filter_select("meetnet", "Selecteer meetnet", locaties_shared, ~meetnet)
  ),
       leaflet(locaties_shared, options = leafletOptions(maxZoom = 11)) %>%
                addTiles() %>%
                addCircleMarkers(stroke = FALSE, label = ~label, radius = 6, opacity = 0.8) %>%
                addPolygons(data = utm5, weight = 1, color = "blue", fill = FALSE, opacity = 0.2)
       )
  )


```

## Monitoringinspanning

```{r}
monitoring_effort_meetnet <- calculate_monitoring_effort(species_group = "libellen",
                                                 aggregation_level = "meetnet")

monitoring_effort_soortgroep <- calculate_monitoring_effort(species_group = "libellen",
                                                 aggregation_level = "species_group") %>%
  mutate(meetnet = "Totaal")

monitoring_effort <- monitoring_effort_meetnet %>%
  bind_rows(monitoring_effort_soortgroep) %>%
  mutate(meetnet = factor(meetnet, levels = c("Beekrombout", "Bosbeekjuffer", "Gevlekte witsnuitlibel", "Hoogveenglanslibel", "Kempense heidelibel", "Maanwaterjuffer", "Rivierrombout", "Sierlijke witsnuitlibel", "Speerwaterjuffer", "Variabele waterjuffer", "Vroege glazenmaker", "Totaal")))
```

```{r, fig.height = 8}

monitoring_effort %>%
  ggplot(aes(x = jaar, y = aantal, colour = monitoringsinspanning, group = monitoringsinspanning)) +
  geom_point() +
  geom_line() +
  facet_wrap(~meetnet, scales = "free_y") +
  ylim(0, NA) +
  theme(legend.position = "bottom", legend.direction = "vertical")
```

