
# (APPENDIX) Bijlagen {-}

# Bijlage: technische beschrijving analysemodel libellen-gebiedstelling {#h:bijlagec}


## Herschaling van de data

Om tot een goede schatting van modelparameters te komen, moeten we het dagnummer in het jaar waarop de telling is uitgevoerd herschalen en centreren. Dit doen we op basis van het dagnummer dat in midden van de telperiode ligt ($dagnr_{mid}$):
$$D = \frac{dagnr - dagnr_{mid}}{28}$$

## Model voor verschillen tussen de jaren

We maken gebruik van een generalised linear mixed model (GLMM), waarbij we aannemen dat het getelde aantal $C_{ldj}$ op locatie $l$, dag $d$ en jaar $j$ een negatief binomiale distributie volgt met gemiddelde $\mu_{ldj}$ en overdispersie parameter $k$.

$$C_{ldj} \sim {NB}(\mu_{ldj}, k)$$

$$E(C_{ldj})=\mu_{ldj}$$
$$var(C_{ldj})=\mu_{ldj}+\frac{\mu_{ldj}^2}{k}$$
We maken gebruik van  onderstaande link functie.

$$\log(\mu_{ldj}) = \eta_{ldj}$$
De verklarende variabelen zijn jaar (als categorische variabele) $J_{j}$, het herschaalde dagnummer binnen een jaar $D_{d}$ en het kwadraat van het herschaalde dagnummer $D_{d}^2$:    

$$\eta_{ldj}= \beta_{0} + \beta_{j}J_{j} + \beta_{1}D_{d} + \beta_{2}D_{d}^2 + b_{l}$$
 $b_{l}$ is een random intercept voor locatie $l$. Het volgt een normale distributie met gemiddelde 0 en variantie $\sigma_{l}^2$:  
 
$$b_{l} \sim {N(0,\sigma_{l}^2)} $$

## Model voor jaarlijkse trend

In dit model gebruiken we jaar als continue variabele $J$. Verder is het model identiek aan het model voor verschillen tussen de jaren. We krijgen dus:

$$\eta_{ldj}= \beta_{0} + \beta_{1}J + \beta_{2}D_{d} + \beta_{3}D_{d}^2 + b_{l}$$
waarbij $e^{\beta_1}$ de relatieve trend weergeeft. 





