
# Dataverkenning Poelkikker


```{r}

analyseset_poelkikker <- read_vc(file = "analyseset_poelkikker", root = "../output/analyseset")

analyseset_poelkikker <- analyseset_poelkikker %>%
  mutate(soort_nl = ifelse(soort_wet == "Pelophylax lessonae/ kl. esculentus", "Poelkikker/bastaardkikker", soort_nl),
         aanwezig = aantal > 0) 

overzicht_poel_bastaard <- analyseset_poelkikker %>%
  filter(soort_nl != "Meerkikker") %>%
  group_by(meetnet, locatie, cluster, visit_id, datum, jaar, meetcyclus) %>%
  summarise(aantal = sum(aantal)) %>%
  ungroup() %>%
  group_by(meetnet, locatie) %>%
  mutate(aanwezig = sum(aantal) > 0) %>%
  ungroup()

```

```{r}
analyseset_poelkikker %>%
  ggplot(aes(y = aantal, x = factor(jaar), colour = aanwezig)) +
  geom_point(alpha = 0.3) +
  stat_summary(fun.data = "mean_cl_boot", colour = "red", size = 1, alpha = 0.4) +
  facet_wrap(~soort_nl, scales = "free_y") +
  labs(x = "jaar")
```




```{r}
overzicht_poel_bastaard %>%
  group_by(meetnet, meetcyclus) %>%
  summarise(n_locaties = n_distinct(locatie), 
            n_clusters = n_distinct(cluster),
            prop_locatie_aanwezig = round(mean(aanwezig), 2),
            aantal_gem = round(mean(aantal))) %>%
  ungroup() %>%
  pivot_longer(cols = c("n_locaties", "n_clusters", "prop_locatie_aanwezig", "aantal_gem"), names_to = "parameter", values_to = "waarde") %>%
  kable(caption = "Overzicht meetcyclus roepkoren Poelkikker + Bastaardkikker") %>%
  kable_styling() %>%
  collapse_rows(c(1,2))

```
```{r}
overzicht_poel_bastaard %>%
  group_by(meetnet, jaar) %>%
  summarise(n_locaties = n_distinct(locatie), 
            n_clusters = n_distinct(cluster),
            prop_locatie_aanwezig = round(mean(aanwezig), 2),
            aantal_gem = round(mean(aantal))) %>%
  ungroup() %>%
  pivot_longer(cols = c("n_locaties", "n_clusters", "prop_locatie_aanwezig", "aantal_gem"), names_to = "parameter", values_to = "waarde") %>%
  kable(caption = "Overzicht per jaar voor roepkoren Poelkikker + Bastaardkikker") %>%
  kable_styling() %>%
  collapse_rows(c(1,2))

```










