

# Dataverkenning

```{r}

analyseset <- analyseset %>%
  filter(primaire_soort) %>%
  mutate(meetcyclus = ifelse(jaar <= 2018, "2016 - 2018",
                             ifelse(jaar <=  2021, "2019 - 2021", "2022 - 2024"))) %>%
  group_by(locatie, protocol) %>%
  mutate(paired = n_distinct(meetcyclus) > 1)

```

## Overzicht tellingen

```{r}
locatie_overzicht <- locatie_detail %>%
  group_by(meetnet) %>%
  mutate(n_clusters = n_distinct(cluster)) %>%
  ungroup() %>%
  group_by(meetnet, n_clusters, is_sample) %>%
  summarise(n_poel = n()) %>%
  ungroup()
  
locatie_overzicht %>%
  kable() %>%
  kable_styling() %>%
  collapse_rows(c(1,2))
```





```{r, fig.height=9}

analyseset %>%
  ggplot(aes(y = poel, x = datum, size = aantal, colour = is_sample, shape = levensstadium)) +
  geom_point(alpha = 0.3) +
  facet_wrap(~cluster, scales = "free_y")
```
```{r}
analyseset %>%
  ggplot(aes(x = is_sample, y = aantal, colour = is_sample)) +
  geom_jitter(alpha = 0.3) +
  stat_summary(fun.data = "mean_cl_boot", colour = "red") +
  facet_wrap(~ levensstadium, scales = "free_y")
```



## Vergelijking meetcycli: alle meetpunten



```{r}
analyseset %>%
  ggplot(aes(x = meetcyclus, y = aantal, colour = is_sample)) +
  geom_jitter(alpha = 0.3) +
  stat_summary(fun.data = "mean_cl_boot", colour = "red") +
  facet_wrap(~ levensstadium, scales = "free_y")
```

```{r}
analyseset %>%
  ggplot(aes(x = aantal, fill = meetcyclus)) +
  geom_density(alpha = 0.5) +
  facet_wrap(~ levensstadium, scales = "free", nrow = 3)
```


## Vergelijking meetcycli: enkel meetnetlocaties


```{r}
analyseset %>%
  filter(is_sample) %>%
  ggplot(aes(x = meetcyclus, y = aantal, colour = is_sample)) +
  geom_jitter(alpha = 0.3) +
  stat_summary(fun.data = "mean_cl_boot", colour = "red") +
  facet_wrap(~ levensstadium, scales = "free_y")
```
```{r}
analyseset %>%
  filter(is_sample) %>%
  ggplot(aes(x = aantal, fill = meetcyclus)) +
  geom_density(alpha = 0.5) +
  facet_wrap(~ levensstadium, scales = "free", nrow = 3)
```

```{r}
analyseset %>%
  filter(is_sample) %>%
  mutate(aantalsklasse = ifelse(aantal == 0, "0", 
                                ifelse(aantal <= 10, "1 - 10", 
                                       ifelse(aantal <= 50, "11 - 50",
                                              ifelse(aantal <= 100, "51 - 100", "> 100"))))) %>%
  mutate(aantalsklasse = factor(aantalsklasse, levels = c("0", "1 - 10", "11 - 50", "51 - 100", "> 100"))) %>%
  ggplot(aes(x = aantalsklasse, fill = meetcyclus)) +
  geom_bar(alpha = 0.5, position = "dodge") +
  facet_wrap(~ levensstadium, scales = "free", nrow = 3)
```



## Vergelijking jaren: enkel meetnetlocaties


```{r}
analyseset %>%
  filter(is_sample) %>%
  ggplot(aes(x = jaar, y = aantal)) +
  geom_point(alpha = 0.3) +
  geom_smooth() +
  stat_summary(fun.data = "mean_cl_boot", colour = "red") +
  facet_wrap(~ levensstadium, scales = "free_y")
```



## Vergelijking gemiddelde aantal adulten per cluster 


```{r}
analyseset %>%
  filter(levensstadium == "adult") %>%
  filter(is_sample) %>%
  ggplot(aes(x = meetcyclus, y = aantal, colour = is_sample)) +
 # geom_jitter(alpha = 0.3) +
  stat_summary(fun.data = "mean_cl_boot", colour = "red") +
  facet_wrap(~ cluster, scales = "free_y")
```
```{r}
analyseset %>%
  filter(is_sample) %>%
  filter(levensstadium == "adult") %>%
  ggplot(aes(x = aantal, fill = meetcyclus)) +
  geom_density(alpha = 0.5) +
  facet_wrap(~ cluster, scales = "free", nrow = 4)
```

## Vergelijking gemiddelde aantal larven per cluster 


```{r}
analyseset %>%
  filter(levensstadium == "larve") %>%
  filter(is_sample) %>%
  ggplot(aes(x = meetcyclus, y = aantal, colour = is_sample)) +
 # geom_jitter(alpha = 0.3) +
  stat_summary(fun.data = "mean_cl_boot", colour = "red") +
  facet_wrap(~ cluster, scales = "free_y")
```

## Zoekinspanning larvetelling

```{r}
analyseset %>%
  filter(larvetelling) %>%
  filter(is_sample) %>%
  ggplot(aes(x = n_catch, fill = meetcyclus)) +
  geom_histogram(alpha = 0.5, position = "dodge")

check_catcheffort <- analyseset %>%
  filter(larvetelling) %>%
  filter(levensstadium == "larve") %>%
  group_by(cluster, poel, meetcyclus) %>%
  mutate(n_visits = n()) %>%
  ungroup() %>%
  select(visit_id, is_sample, cluster, poel, meetcyclus, n_visits, datum, n_catch, levensstadium, aantal)
  
```

```{r}
check_catcheffort_missing_value <- check_catcheffort %>%
  group_by(meetcyclus, is_sample) %>%
  summarise(n_records = n(),
            prop_missing = round(sum(is.na(n_catch))/ n(), 2),
            prop_ingevuld = round(sum(!is.na(n_catch))/ n(), 2))

check_catcheffort_missing_value %>%
  kable(caption = "Proportie van de observatie waarbij 'aantal keer geschept' niet werd ingevuld per meetcyclus") %>%
  kable_styling() %>%
  collapse_rows(1)
```

```{r}
catcheffort_missing <- check_catcheffort %>%
  filter(is.na(n_catch)) %>%
  select(visit_id, cluster, poel, is_sample, datum, aantal) %>%
  left_join(select(visits, visit_id, hoofdteller), by = "visit_id") %>%
  arrange(datum)

catcheffort_missing %>%
  write_csv2("../output/boomkikkerlarve_aantalscheppen_ontbreekt.csv")

catcheffort_missing %>%
  select(-hoofdteller) %>%
  datatable(rownames = FALSE)
```

```{r, fig.height= 9}
check_catcheffort %>%
  filter(is_sample) %>%
  ggplot(aes(x = n_catch, y = poel, colour = meetcyclus, shape = meetcyclus)) +
  geom_point(alpha = 0.5, size = 4) +
  facet_wrap(~ cluster, scales = "free_y")
```




```{r}


analyseset %>%
  filter(levensstadium == "larve") %>%
  filter(is_sample) %>%
  filter(!is.na(n_catch)) %>%
  mutate(aantal_10catch = aantal / n_catch * 10) %>%
  ggplot(aes(x = meetcyclus, y = aantal_10catch, colour = is_sample)) +
  stat_summary(fun.data = "mean_cl_boot", colour = "red") 


analyseset %>%
  filter(levensstadium == "larve") %>%
  filter(is_sample) %>%
  mutate(aantal_10catch = aantal / n_catch * 10) %>%
  ggplot(aes(x = meetcyclus, y = aantal_10catch, colour = is_sample)) +
  stat_summary(fun.data = "mean_cl_boot", colour = "red") 
```

##



```{r}
mean_sample <- analyseset %>%
  filter(is_sample) %>%
  filter(primaire_soort) %>%
  group_by(levensstadium, meetcyclus) %>%
  summarise(mean_count = round(mean(aantal, na.rm = TRUE), 2),
            se = sqrt(var(aantal, na.rm = TRUE)/n()),
            mean_n_catch = round(mean(n_catch, na.rm = TRUE), 2),
            occurence = round(sum(aantal > 0, na.rm = TRUE)/ n(), 2),
            n_bezoeken = n(),
            n_locaties = n_distinct(locatie)) %>%
  ungroup() %>%
  mutate(mean_count = str_c(mean_count, " [", round(mean_count - 1.96 * se, 2), " - ", round(mean_count + 1.96 * se, 2), "]"))

mean_larve_10schep<- analyseset %>%
  filter(primaire_soort) %>%
  filter(is_sample) %>%
  filter(levensstadium == "larve") %>%
  filter(!is.na(n_catch)) %>%
  mutate(aantal = aantal/n_catch * 10) %>%
  group_by(cluster, locatie) %>%
  filter(n_distinct(meetcyclus) >=2 ) %>%
  ungroup() %>%
  group_by(levensstadium, meetcyclus) %>%
  summarise(mean_count = round(mean(aantal, na.rm = TRUE), 2),
            se = sqrt(var(aantal, na.rm = TRUE)/n()),
            occurence = round(sum(aantal > 0, na.rm = TRUE)/ n(), 2),
            n_bezoeken = n(),
            n_locaties = n_distinct(locatie)) %>%
  ungroup()  %>%
  mutate(mean_count = str_c(mean_count, " [", round(mean_count - 1.96 * se, 2), " - ", round(mean_count + 1.96 * se, 2), "]")) %>%
  mutate(levensstadium = "larve_per10schep")

mean_sample %>%
  bind_rows(mean_larve_10schep) %>%
  arrange(levensstadium) %>%
  mutate(mean_n_catch = ifelse(levensstadium == "larve", mean_n_catch, NA)) %>%
  select(-se) %>%
  kable %>%
  kable_styling() %>%
  collapse_rows(c(1, 2))
```



## Modelering

```{r}

analyseset <- analyseset %>%
  group_by(meetnet, protocol) %>%
  mutate(doy_scaled2 = doy - min(doy) +1) %>%
  ungroup() %>%
  mutate(jaar_scaled = jaar - min(jaar) + 1)

analyseset_adult <- analyseset %>%
  filter(levensstadium == "adult")


indexmodel_doyrw2_jaarrw1_iid <- inla(aantal ~ meetcyclus  + 
                                f(doy_scaled2, model = "rw2", 
                                  hyper = list(theta = list(prior = "pc.prec", param = c(0.01, 0.05)))) + 
                                 f(locatie, model = "iid", 
                                   hyper = list(theta = list(prior = "pc.prec", param = c(1, 0.05))))  + 
                                 f(cluster, model = "iid", 
                                   hyper = list(theta = list(prior = "pc.prec", param = c(1, 0.05)))),
                              family = "nbinomial",
                              data = data_combine,
                              control.compute = list(config = TRUE, waic = TRUE),
                              control.predictor = list(compute = TRUE))
```

