

# Boomkikker

```{r}
species <- "Boomkikker"
species_group <- "amfibieën"
protocol_selection <- "Padden en kikkers - Roepkoren"
name_analysis <- "Boomkikker"

set.seed(47830)
```

## Selectie analyseset

```{r select data, warning = FALSE}

locatie_detail <- get_locations_smp() %>%
  st_drop_geometry() %>%
  filter(locatie_type == "locatie") %>%
  select(meetnet, locatie, is_active, is_sample)

visits <- get_visits_smp(species_group)
counts <- get_counts_smp(species_group = species_group, count_aggregation = "individuals") %>%
  filter(primaire_soort)

count_period <- get_characteristics_smp(species_group = species_group) %>%
  mutate(doy_min = as.numeric(format(start_telperiode, "%j")),
         doy_max = as.numeric(format(einde_telperiode, "%j")),
         doy_mid = doy_min + round((doy_max - doy_min)/2, 0)) %>%
  distinct(meetnet, protocol, doy_min, doy_max, doy_mid)

meetnetten_selection <- visits %>%
  filter(meetnet == species) %>%
  group_by(meetnet, protocol) %>%
  summarise(n_jaar = n_distinct(jaar)) %>%
  filter(n_jaar >= 3)

visits_selection <- visits %>%
  filter(meetnet == species) %>%
  filter(protocol == protocol_selection) %>%
  left_join(locatie_detail, by = c("meetnet", "locatie")) %>%
  filter(voor_analyse & !is.na(is_active)) %>%
  left_join(count_period, by = c("meetnet", "protocol")) %>%
  mutate(doy_scaled = (doy - doy_mid)/28,
         fjaar = factor(jaar),
         cluster = ifelse(str_detect(locatie, " - "), 
                          str_sub(locatie,  end = str_locate(locatie, " - ")),
                          locatie),
         cluster = str_remove_all(cluster, str_c(as.character(c(0:9)), collapse = "|")),
         cluster = str_trim(cluster)) %>%
  group_by(soortgroep, meetnet, protocol, locatie, jaar, fjaar) %>%
  mutate(n_obs = n_distinct(visit_id)) %>%
  ungroup()

counts_selection <- visits_selection %>%
  select(soortgroep, meetnet, protocol, cluster, locatie, jaar, datum, doy, doy_scaled, doy_min, doy_max, doy_mid, visit_id, n_obs, voor_analyse, is_active, is_sample, bezoek_status, bezoek_status_oud) %>%
  left_join(select(counts, visit_id, soort_nl, soort_wet, aantal), by = "visit_id")
       
```


```{r}

counts_analysis <- counts_selection %>%

  group_by(meetnet, locatie) %>%
  mutate(n_jaren = n_distinct(jaar),
            max_count = max(aantal)) %>%
  ungroup() %>%
 # filter(n_jaren > 1 & max_count > 0) %>%
  mutate(fjaar = factor(jaar),
         locatie = factor(locatie),
         doy_scaled_2 = doy_scaled * doy_scaled)
  
analyseset_by_species <- counts_analysis %>%
  group_by(meetnet) %>%
  nest()


``` 

```{r}

write_vc(counts_analysis, file = "analyseset", root = here(str_c("analysis_", species_group, "/output/temp")), sorting = c("meetnet", "locatie", "visit_id"), strict = FALSE)
  
```

## Dataverkenning

```{r}
analyseset_species_sample <- counts_analysis %>%
  filter(meetnet == "Boomkikker") %>%
  filter(is_sample) %>%
  filter(cluster != "Merkske")

n_loc_sample <- n_distinct(analyseset_species_sample$locatie)

n_clusters_sample <- n_distinct(analyseset_species_sample$cluster)

analyseset_species_all <- counts_analysis %>%
  filter(meetnet == "Boomkikker") 

n_loc_all <- n_distinct(analyseset_species_all$locatie)

n_clusters_all <- n_distinct(analyseset_species_all$cluster)

analyseset_species_rep <- counts_analysis %>%
  filter(meetnet == "Boomkikker") %>%
  filter(is_sample) %>%
  filter(cluster != "Merkske") %>%
  filter(n_jaren > 1)

```

```{r, fig.height=9}

analyseset_species_all %>%
  ggplot(aes(y = locatie, x = datum, size = aantal, colour = is_sample)) +
  geom_point(alpha = 0.3) +
  facet_wrap(~cluster, scales = "free_y")
```


```{r}
analyseset_species_sample %>%
  ggplot(aes(x = fjaar, y = aantal)) +
  geom_boxplot() +
  coord_flip()
```

```{r}
mean_sample <- analyseset_species_sample %>%
  group_by(jaar) %>%
  summarise(mean = mean(aantal)) %>%
  ungroup()

mean_all <- analyseset_species_all %>%
  group_by(jaar) %>%
  summarise(mean = mean(aantal)) %>%
  ungroup()

mean_rep <-  analyseset_species_rep %>%
  group_by(jaar) %>%
  summarise(mean = mean(aantal)) %>%
  ungroup()
```



## Modelering

```{r test, eval = FALSE}

prec.prior <- list(prec = list(param = c(0.001, 0.001)))

model_nested_inla <- inla(aantal ~ fjaar + doy_scaled + doy_scaled_2 + f(cluster, model = "iid", hyper = prec.prior) + f(locatie, model = "iid", hyper = prec.prior),
                                      family = "nbinomial",
                                      data = analyseset_species_sample,
                                      control.compute = list(config = TRUE, waic = TRUE),
                                      control.predictor = list(compute = TRUE))

analyseset_species_sample <- analyseset_species_sample %>%
    mutate(fjaar = factor(jaar),
           locatie = as.character(locatie),
           locatie = as.factor(locatie),
           min_year = min(jaar),
           year_scaled = jaar - min_year)

trendmodel_nested_inla <- inla(aantal ~ year_scaled + doy_scaled + doy_scaled_2 + f(cluster, model = "iid", hyper = prec.prior) + f(locatie, model = "iid", hyper = prec.prior),
                                      family = "nbinomial",
                                      data = analyseset_species_sample,
                                      control.compute = list(config = TRUE, waic = TRUE),
                                      control.predictor = list(compute = TRUE))


  model.matrix(~fjaar, analyseset_species) %>% # create dummy variable for year
    as.data.frame() %>%
    select(-1) %>% # drop intercept
    bind_cols(analyseset_species) %>%
    mutate(loc_id = as.integer(factor(locatie)),
           clust_id = as.integer(factor(cluster))) -> analyseset_species_bru

model_nested_inlabru <- bru(aantal ~ fjaar2017 + fjaar2018 + fjaar2019 + fjaar2020 + doy_scaled + doy_scaled_2 +  site(map = loc_id, model = "iid",  n = n_loc_sample, hyper = prec.prior) + cluster(map = clust_id, model = "iid", hyper = prec.prior, n = n_clusters_sample) ,
                                      family = "nbinomial",
                                      data = analyseset_species_bru)

summary_inla <- model_nested_inla$summary.fixed %>%
  rownames_to_column("parameter") %>%
  mutate(method = "inla") %>%
  select(method, parameter, mean, sd)

summary_inlabru <- model_nested_inlabru$summary.fixed %>%
  rownames_to_column("parameter") %>%
  mutate(method = "inlabru") %>%
  select(method, parameter, mean, sd)
  
model_nested_lme <- glmer.nb(aantal ~ fjaar + doy_scaled + doy_scaled_2 + (1|locatie) + (1|cluster),
                         data = analyseset_species)

summary_lme <- (summary(model_nested_lme))$coefficients %>%
  as.data.frame() %>%
  rownames_to_column("parameter") %>%
  mutate(method = "lme") %>%
  select(method, parameter, mean = "Estimate", sd = "Std. Error")
  
compare_fixed <- bind_rows(summary_inla,
                     summary_lme, summary_inlabru) %>%
  mutate(index = exp(mean))


var_random_effect_lme <- VarCorr(model_nested_lme) %>%
  as.data.frame() %>%
  mutate(method = "lme") %>%
  select(method, group = grp, var = vcov)

var_random_effect_inla <- model_nested_inla$summary.hyperpar %>%
  rownames_to_column("group") %>%
  mutate(group = str_remove(group, "Precision for ")) %>%
  filter(group %in% c("cluster", "locatie")) %>%
  mutate(method = "inla",
         var = 1/mean) %>%
  select(method, group, var)

compare_var_random_effect <- bind_rows(var_random_effect_lme,
                     var_random_effect_inla) %>%
  mutate(var = round(var, 5))
  
index_inla <- derive_index_inla(analyseset_species, model_nested_inla) %>%
  mutate(method = "inla") %>%
  select(method, parameter, jaar, mean, sd)

index_inlabru <- derive_index_inlabru(analyseset_species, model_nested_inlabru) %>%
  mutate(method = "inlabru") %>%
  select(method, parameter, jaar, mean, sd)

compare_index <- bind_rows(index_inla, index_inlabru)

trend <- derive_trend(analyseset_species = analyseset_species_all, trendmodel_nested_inla)

```



```{r}
models_inlabru <- analyseset_by_species %>% 
  mutate(indexmodel = map(data, fit_indexmodel_nbinom_inlabru),
         trendmodel = map(data, fit_trendmodel_nbinom_inlabru))

models_inla <- analyseset_by_species %>%
  mutate(indexmodel = map(data, fit_indexmodel_nbinom_inla))

results_indexmodel <- models_inla %>%
  transmute(index = map2(data, indexmodel, derive_index_inla),
            max_count = map2(data, indexmodel, derive_max_count_inla))

results_trendmodel <- models_inlabru %>%
  transmute(trend = map2(data, trendmodel, derive_trend_inlabru),
            waic_index =  map2(data, indexmodel, get_waic_inlabru),
            waic_trend = map2(data, trendmodel, get_waic_inlabru))

```

```{r}
results_index <- results_indexmodel %>%
  select(meetnet, index) %>%
  unnest(index)

results_max_count <- results_indexmodel %>%
  select(meetnet, max_count) %>%
  unnest(max_count)

# results_diff_years <- results_indexmodel %>%
#   select(meetnet, diff_years) %>%
#   unnest(diff_years)

results_trend <- results_trendmodel %>%
  select(meetnet, trend) %>%
  unnest(trend)

results_waic_index <- results_trendmodel %>%
  select(meetnet, waic_index) %>%
  unnest(waic_index) %>%
  mutate(model = "indexmodel")

results_waic_trend <- results_trendmodel %>%
  select(meetnet, waic_trend) %>%
  unnest(waic_trend) %>%
  mutate(model = "trendmodel")

results_waic <- bind_rows(results_waic_index, 
                         results_waic_trend) %>%
  spread(key = "model", value = "waic") %>%
  mutate(diff_waic = trendmodel - indexmodel,
         type_trend = ifelse(diff_waic > 0,
                               "Niet lineair",
                               ifelse(diff_waic > -2,
                                      "Quasi lineair", "Lineair")))

```

```{r}

bind_rows(results_index, 
          results_max_count) %>%
  write_vc(file = "results_indexmodel", 
         root = here(str_c("analysis_", species_group, "/output/temp")), 
         sorting = c("parameter", "soort_nl", "jaar"),
         strict = FALSE)

results_trend %>%
  write_vc(file = "results_trendmodel", 
         root = here(str_c("analysis_", species_group, "/output/temp")), 
         sorting = c("parameter", "soort_nl"), strict = FALSE)

results_waic %>%
  write_vc(file = "results_waic", 
         root = here(str_c("analysis_", species_group, "/output/temp")), 
         sorting = c("parameter", "soort_nl"),
         strict = FALSE)

```


## Validatie

```{r}
model_validation <- models_inla %>%
  transmute(dispersion_check_model = map(indexmodel, dispersion_check),
            distribution_check_model = map(indexmodel, fast_distribution_check),
            iid_check = map(indexmodel, check_random_effect)
            )


dispersion <- model_validation %>%
  transmute(dispersion_data = map(dispersion_check_model, "data"),
            dispersion_model = map(dispersion_check_model, "model")) %>%
  select(meetnet, dispersion_data, dispersion_model) %>%
  unnest(c(dispersion_data, dispersion_model))

distribution <- model_validation %>%
  select(meetnet, distribution_check_model) %>%
  unnest(distribution_check_model) %>%
  filter(lcl < 0.98 & ucl < 1)

iid_checked <- model_validation %>%
  select(meetnet, iid_check) %>%
  unnest(iid_check)

```

### Dispersie

```{r}

ggplot(data = dispersion, aes(x = dispersion_model)) +
      geom_density() +
      geom_vline(data = dispersion, aes(xintercept = dispersion_data), linetype = 2) +
      facet_wrap(~meetnet, scales = "free_x")
     
```

### Distributie

```{r, fig.height= 8}
distribution %>%
  mutate(
      median = .data$ecdf / .data$median,
      lcl = .data$ecdf / .data$lcl,
      ucl = .data$ecdf / .data$ucl
    ) %>%
  ggplot(aes_string(x = "x", y = "median")) +
   # geom_blank(data = data.frame(x = min(x$x), median = c(0.95, 1.05))) +
    geom_hline(yintercept = 1, linetype = 2) +
    geom_line(aes_string(y = "lcl"), linetype = 3, alpha = 0.5) +
    geom_line(aes_string(y = "ucl"), linetype = 3, alpha = 0.5) +
    geom_ribbon(alpha = 0.1, aes_string(ymin = "lcl", ymax = "ucl")) +
    geom_line() +
    scale_y_continuous("observed / expected", labels = scales::percent) +
    facet_wrap(~meetnet, scales = "free", ncol = 2)
```

### Random effect

```{r}

iid_checked_plot <- iid_checked %>%
  group_by(meetnet) %>%
  mutate(x_c = sim_iid - mean(sim_iid),
         y = exp(x_c + log(1))) %>%
  ungroup()

iid_checked_plot %>%
  mutate(sigma_tekst = str_c("sigma = ", round(sigma, 3))) %>%
  ggplot(aes(x = y)) +
      geom_density() +
      scale_x_continuous("relative effect", labels = scales::percent) +
      facet_wrap(~meetnet + sigma_tekst, scales = "free")
    
```

```{r}
iid_checked_plot %>%
  filter(meetnet == "Speerwaterjuffer") %>%
  mutate(sigma_tekst = str_c("sigma = ", round(sigma, 3))) %>%
  ggplot(aes(x = y)) +
      geom_density() +
      scale_x_continuous("relative effect", labels = scales::percent) +
      facet_wrap(~meetnet + sigma_tekst, scales = "free")
```



## Visualisatie model

```{r}
model_simulate <- models_inlabru %>%
  transmute(data_simulated = map2(data, indexmodel, simulate_data_model_inlabru))

results_data_simulated <- model_simulate %>%
  unnest(data_simulated)
```




```{r, warning=FALSE, fig.height= 9}

ggplot(data = results_data_simulated, aes(x = doy)) + 
  geom_line(aes(y = mean, group = loc_id, colour = factor(loc_id)), linetype = 2 ) +
  geom_point(aes(y = y_obs), alpha = 0.5, size = 1) +
  geom_line(aes(y = mean_year), size = 1, colour = "black") +
  geom_ribbon(aes(ymin = lci_0.95_year, ymax = uci_0.95_year), alpha = 0.3) +
  facet_grid(soort_nl ~ jaar, scales = "free") +
  theme(legend.position = "none")
```

### Maanwaterjuffer

```{r, fig.height= 9}


ggplot(data = filter(results_data_simulated, meetnet == "Maanwaterjuffer"), aes(x = doy)) + 
  geom_line(aes(y = mean, group = loc_id, colour = factor(loc_id)), linetype = 2 ) +
  geom_point(aes(y = y_obs), alpha = 0.5, size = 1) +
  geom_line(aes(y = mean_year), size = 1, colour = "black") +
  geom_ribbon(aes(ymin = lci_0.95_year, ymax = uci_0.95_year), alpha = 0.3) +
  facet_wrap( ~ jaar) +
  theme(legend.position = "none")
```

### Speerwaterjuffer

```{r, fig.height= 9}

ggplot(data = filter(results_data_simulated, meetnet == "Speerwaterjuffer"), aes(x = doy)) + 
  geom_line(aes(y = mean, group = loc_id, colour = factor(loc_id)), linetype = 2, alpha = 0.2) +
  geom_point(aes(y = y_obs), alpha = 0.5, size = 1) +
  geom_line(aes(y = mean_year), size = 1, colour = "black") +
  geom_ribbon(aes(ymin = lci_0.95_year, ymax = uci_0.95_year), alpha = 0.3) +
  facet_wrap( ~ jaar) +
  theme(legend.position = "none")
```
```{r, fig.width= 9}
# analyseset_species <- counts_analysis %>%
#   filter(meetnet == "Speerwaterjuffer")
# 
# analyseset_species %>%
#   ggplot(aes(x = jaar, y = aantal)) +
#   geom_point() +
#   facet_wrap(~locatie)

counts_analysis %>%
  ggplot(aes(x = locatie, y =aantal)) +
  geom_point(alpha = 0.4, size = 2) +
  coord_flip() +
  facet_wrap(~meetnet, scales = "free_y", ncol = 1)
  

```



## Documenteer analyse

```{r}

mypath <- here(str_c("analysis_", species_group, "/output/temp"))

hashes <-
    tibble(filepath = str_c(mypath, "/",
        list.files(path = mypath,
            recursive = TRUE)
      )) %>%
    mutate(name_analysis = name_analysis,
           version = Sys.Date(),
           filename = str_match(filepath, "(.+\\/)*(.+)")[,3],
           md5 = map(filepath, function(x) {
                           file(x) %>% md5 %>% str_c(collapse = '')
                         }) %>% as.character,
           sha256 = map(filepath, function(x) {
                          file(x) %>% sha256 %>% str_c(collapse = '')
                          }) %>% as.character
           ) %>%
    select(name_analysis,
           version,
           filename,
           md5,
           sha256)

file_name <- here(str_c("analysis_", species_group, "/output/analysis_hashes.csv"))

if (!file.exists(file_name)) {
  
  new_analysis <- TRUE
  
  analysis_hashes <- hashes

} else {
  
  analysis_hashes <- read_csv(file_name)
  
  hashes_new <- hashes %>%
    anti_join(analysis_hashes, by = c("name_analysis", "filename", "md5", "sha256"))
  
  new_analysis <- nrow(hashes_new) > 0
  
  analysis_hashes <- bind_rows(analysis_hashes,
                               hashes)
  
}

if (new_analysis) {
  
  new_path <- here(str_c("analysis_", species_group, "/output/", name_analysis, "_", Sys.Date()))
  
  if (!dir.exists(new_path)) {
    
    dir.create(new_path)
    file.copy(from = str_c(mypath, "/analyseset.tsv"), to = str_c(new_path, "/analyseset.tsv"), overwrite = TRUE)
    file.copy(from = str_c(mypath, "/analyseset.yml"), to = str_c(new_path, "/analyseset.yml"), overwrite = TRUE)
    file.copy(from = str_c(mypath, "/results_indexmodel.tsv"), to = str_c(new_path, "/results_indexmodel.tsv"), overwrite = TRUE)
    file.copy(from = str_c(mypath, "/results_indexmodel.yml"), to = str_c(new_path, "/results_indexmodel.yml"), overwrite = TRUE)
    file.copy(from = str_c(mypath, "/results_trendmodel.tsv"), to = str_c(new_path, "/results_trendmodel.tsv"), overwrite = TRUE)
    file.copy(from = str_c(mypath, "/results_trendmodel.yml"), to = str_c(new_path, "/results_trendmodel.yml"), overwrite = TRUE)
    file.copy(from = str_c(mypath, "/results_waic.tsv"), to = str_c(new_path, "/results_waic.tsv"), overwrite = TRUE)
    file.copy(from = str_c(mypath, "/results_waic.yml"), to = str_c(new_path, "/results_waic.yml"), overwrite = TRUE)
  }
  
  analysis_hashes %>%
    write_csv(file_name)
  
}

```



### Effect van lengte tijdsreeks op index

#### Gevlekte witsnuitlibel

```{r}

soort <- "Gevlekte witsnuitlibel"

analyseset_soort <- counts_analysis %>%
  filter(meetnet == soort)

model_soort <- analyseset_soort %>%
  fit_indexmodel_nbinom_inlabru() 
  
index_soort_2020 <- derive_index_inlabru(analyseset_soort, model_soort) %>%
  mutate(tijdsreeks = "2016-2020")

analyseset_soort <- counts_analysis %>%
  filter(meetnet == soort) %>%
  filter(jaar <= 2019)

model_soort <- analyseset_soort %>%
  fit_indexmodel_nbinom_inlabru() 
  
index_soort_2019 <- derive_index_inlabru(analyseset_soort, model_soort) %>%
  mutate(tijdsreeks = "2016-2019")

analyseset_soort <- counts_analysis %>%
  filter(meetnet == soort) %>%
  filter(jaar <= 2018)

model_soort <- analyseset_soort %>%
  fit_indexmodel_nbinom_inlabru() 
  
index_soort_2018 <- derive_index_inlabru(analyseset_soort, model_soort) %>%
  mutate(tijdsreeks = "2016-2018")

index_soort <- bind_rows(
  index_soort_2018,
  index_soort_2019,
  index_soort_2020
  
)

```



```{r}

index_soort %>%
  mutate(ref_jaar_tekst = str_c("ref. jaar = ", ref_jaar)) %>%
  filter(parameter == "index") %>%
  ggplot(aes(y = mean, ymin = lcl_0.95, ymax = ucl_0.95, x = as.character(jaar), group = soort_nl)) +
  geom_point() +
  geom_errorbar(width = 0.1) +
  geom_hline(yintercept = 1, linetype = 3) +
  geom_line( colour = inbo.steun.blauw, linetype = 2) +
  #geom_ribbon(alpha = 0.2) + 
  labs(y = "Jaarlijkse index", x = "Jaar") +
  #scale_x_continuous(breaks= c(2017, 2018)) +
  scale_y_continuous(labels = scales::percent, limits = c(0,NA)) +
  facet_wrap(~ tijdsreeks + ref_jaar_tekst)
```

#### Maanwaterjuffer

```{r}

soort <- "Maanwaterjuffer"

analyseset_soort <- counts_analysis %>%
  filter(meetnet == soort)

model_soort <- analyseset_soort %>%
  fit_indexmodel_nbinom_inlabru() 
  
index_soort_2020 <- derive_index_inlabru(analyseset_soort, model_soort) %>%
  mutate(tijdsreeks = "2016-2020")

analyseset_soort <- counts_analysis %>%
  filter(meetnet == soort) %>%
  filter(jaar <= 2019)

model_soort <- analyseset_soort %>%
  fit_indexmodel_nbinom_inlabru() 
  
index_soort_2019 <- derive_index_inlabru(analyseset_soort, model_soort) %>%
  mutate(tijdsreeks = "2016-2019")

analyseset_soort <- counts_analysis %>%
  filter(meetnet == soort) %>%
  filter(jaar <= 2018)

model_soort <- analyseset_soort %>%
  fit_indexmodel_nbinom_inlabru() 
  
index_soort_2018 <- derive_index_inlabru(analyseset_soort, model_soort) %>%
  mutate(tijdsreeks = "2016-2018")

index_soort <- bind_rows(
  index_soort_2018,
  index_soort_2019,
  index_soort_2020
  
)

```



```{r}

index_soort %>%
  mutate(ref_jaar_tekst = str_c("ref. jaar = ", ref_jaar)) %>%
  filter(parameter == "index") %>%
  ggplot(aes(y = mean, ymin = lcl_0.95, ymax = ucl_0.95, x = as.character(jaar), group = soort_nl)) +
  geom_point() +
  geom_errorbar(width = 0.1) +
  geom_hline(yintercept = 1, linetype = 3) +
  geom_line( colour = inbo.steun.blauw, linetype = 2) +
  #geom_ribbon(alpha = 0.2) + 
  labs(y = "Jaarlijkse index", x = "Jaar") +
  #scale_x_continuous(breaks= c(2017, 2018)) +
  scale_y_continuous(labels = scales::percent, limits = c(0,NA)) +
  facet_wrap(~ tijdsreeks + ref_jaar_tekst)
```

