project:
  type: book
  preview:
    port: 4201
    browser: true
  render:
  - '*.md'
  - '*.qmd'
  - '!LICENSE.md'
  - '!README.md'
  output-dir: output/flandersqmd_dagvlinders
  post-render: _extensions/inbo/flandersqmd-book/filters/post_render.R
execute:
  echo: false
  warnings: false
  errors: true
  message: false
  freeze: auto
  cache: false
format:
  flandersqmd-book-html: default
  flandersqmd-book-pdf: default
lang: nl-BE
flandersqmd:
  license: CC-BY-4.0
  entity: INBO
  level: 2
  title: Trends op basis van de dagvlindermeetnetten (2016 - 2025)
  subtitle: Citizen science monitoring in Vlaanderen
  shorttitle: trends-dagvlinders
  author:
  - name:
      given: Toon
      family: Westra
    email: toon.westra@inbo.be
    orcid: 0000-0003-2478-9459
    affiliation:
    - Instituut voor Natuur- en Bosonderzoek (INBO)
    corresponding: true
  - name:
      given: Dirk
      family: Maes
    email: dirk.maes@inbo.be
    orcid: 0000-0002-7947-3788
    affiliation:
    - Instituut voor Natuur- en Bosonderzoek (INBO)
  - name:
      given: Wim
      family: Veraghtert
    email: hannes.ledegen@natuurpunt.be
    affiliation:
    - Natuurpunt Studie
  - name:
      given: Sam
      family: Van de Poel
    email: sam.vandepoel@natuurpunt.be
    orcid: 0000-0001-6251-3766
    affiliation:
    - Natuurpunt Studie
  - name:
      given: Thierry
      family: Onkelinx
    email: thierry.onkelinx@inbo.be
    orcid: 0000-0001-8804-4216
    affiliation:
    - Instituut voor Natuur- en Bosonderzoek (INBO)
  reviewer:
  - name:
      given: Stijn
      family: Van Onsem
    email: geert.deknijf@inbo.be
    orcid: 0000-0002-7958-1420
    affiliation:
    - Instituut voor Natuur- en Bosonderzoek (INBO)
  rightsholder:
  - name:
      given: Instituut voor Natuur- en Bosonderzoek (INBO)
    email: info@inbo.be
    ror: 00j54wy13
  funder:
  - name:
      given: Instituut voor Natuur- en Bosonderzoek (INBO)
    email: info@inbo.be
    ror: 00j54wy13
  community: inbo
  publication_type: publication-report
  publisher: INBO
  keywords: monitoring
  public_report: true
  reportnr: x.xx
  doi: 10.5281/zenodo.842223
  year: 2026
  colophon: true
  floatbarrier: section
  depotnr: 'xx'
  coverdescription: Bruine eikenpage
book:
  downloads: pdf
  open-graph: true
  body-footer: '{{< footer >}}'
  navbar:
    pinned: true
    right:
    - icon: facebook
      href: https://www.facebook.com/INBOVlaanderen/
    left:
    - text: Cover
      file: index.md
  chapters:
  - index.md
  - samenvatting.md
  - abstract.md
  - inleiding.qmd
  - methods.qmd
  - aantallen.qmd
  - results.qmd
  - referenties.md
  appendices:
  - bijlage1.qmd
  - bijlage_r.qmd
bibliography: references.bib
