project:
  type: book
  preview:
    port: 4201
    browser: true
  render:
    - "*.md"
    - "*.qmd"
    - "!LICENSE.md" #ignore LICENSE.md
    - "!README.md" #ignore README.md
  output-dir: output

execute:
  echo: false
  message: false
  warning: false
  freeze: auto

lang: nl-BE #en-GB , fr-FR

bibliography: references.bib

format:
  flandersqmd-book-html: default
  flandersqmd-book-pdf: default

flandersqmd:
  entity: INBO
  level: 2
  title: Trends libellenmeetnetten Vlaanderen
  subtitle: The optional subtitle
  author:
    - name:
        given: Toon
        family: Westra
      email: Toon.Westra@inbo.be
      corresponding: true
      orcid: 0000-0002-1825-0097
      affiliation:
        - Instituut voor Natuur- en Bosonderzoek
    - name:
        given: Geert
        family: De Knijf
      email: second.author@vlaanderen.be
      corresponding: true
      orcid: 0000-0002-1825-0097
      affiliation:
        - Government of Flanders
    - name:
        given: Third
        family: Author
      email: third.author@vlaanderen.be
      orcid: 0000-0002-1825-0097
      affiliation:
        - Government of Flanders
  reviewer:
    - name:
        given: Stijn
        family: Van Onsem
      email: reviewer@vlaanderen.be
      orcid: 0000-0002-1825-0097
      affiliation:
        - Government of Flanders
  year: 2026
  reportnr: 3.14
  coverphoto: media/cover.png
  coverdescription: libel
  doi: 10.5281/zenodo.842223
  linenr: false
  public_report: true
  colophon: true

book:
  downloads: pdf
  open-graph: true
  sidebar:
    logo: media/cover.png
  body-footer: '{{< footer >}}'
  chapters:
    - index.md
    - summary.qmd
    - introduction.qmd
    - methods.qmd
    - references.qmd
prefer-html: true